<?php

/**
 * Base static class for performing query and update operations on the 'payment' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu 26 Apr 2012 01:25:34 PM EDT
 *
 * @package    lib.model.om
 */
abstract class BasePaymentPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'payment';

	/** the related Propel class for this table */
	const OM_CLASS = 'Payment';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.Payment';

	/** the related TableMap class for this table */
	const TM_CLASS = 'PaymentTableMap';
	
	/** The total number of columns. */
	const NUM_COLUMNS = 34;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the PAYMENT_ID field */
	const PAYMENT_ID = 'payment.PAYMENT_ID';

	/** the column name for the FK_FILM_ID field */
	const FK_FILM_ID = 'payment.FK_FILM_ID';

	/** the column name for the FK_SCREENING_ID field */
	const FK_SCREENING_ID = 'payment.FK_SCREENING_ID';

	/** the column name for the FK_SCREENING_NAME field */
	const FK_SCREENING_NAME = 'payment.FK_SCREENING_NAME';

	/** the column name for the FK_AUDIENCE_ID field */
	const FK_AUDIENCE_ID = 'payment.FK_AUDIENCE_ID';

	/** the column name for the FK_SUBSCRIPTION_ID field */
	const FK_SUBSCRIPTION_ID = 'payment.FK_SUBSCRIPTION_ID';

	/** the column name for the FK_USER_ID field */
	const FK_USER_ID = 'payment.FK_USER_ID';

	/** the column name for the PAYMENT_UNIQUE_CODE field */
	const PAYMENT_UNIQUE_CODE = 'payment.PAYMENT_UNIQUE_CODE';

	/** the column name for the PAYMENT_TYPE field */
	const PAYMENT_TYPE = 'payment.PAYMENT_TYPE';

	/** the column name for the PAYMENT_FIRST_NAME field */
	const PAYMENT_FIRST_NAME = 'payment.PAYMENT_FIRST_NAME';

	/** the column name for the PAYMENT_LAST_NAME field */
	const PAYMENT_LAST_NAME = 'payment.PAYMENT_LAST_NAME';

	/** the column name for the PAYMENT_EMAIL field */
	const PAYMENT_EMAIL = 'payment.PAYMENT_EMAIL';

	/** the column name for the PAYMENT_B_ADDR_1 field */
	const PAYMENT_B_ADDR_1 = 'payment.PAYMENT_B_ADDR_1';

	/** the column name for the PAYMENT_B_ADDR_2 field */
	const PAYMENT_B_ADDR_2 = 'payment.PAYMENT_B_ADDR_2';

	/** the column name for the PAYMENT_B_CITY field */
	const PAYMENT_B_CITY = 'payment.PAYMENT_B_CITY';

	/** the column name for the PAYMENT_B_STATE field */
	const PAYMENT_B_STATE = 'payment.PAYMENT_B_STATE';

	/** the column name for the PAYMENT_B_ZIPCODE field */
	const PAYMENT_B_ZIPCODE = 'payment.PAYMENT_B_ZIPCODE';

	/** the column name for the PAYMENT_B_COUNTRY field */
	const PAYMENT_B_COUNTRY = 'payment.PAYMENT_B_COUNTRY';

	/** the column name for the PAYMENT_STATUS field */
	const PAYMENT_STATUS = 'payment.PAYMENT_STATUS';

	/** the column name for the PAYMENT_AMOUNT field */
	const PAYMENT_AMOUNT = 'payment.PAYMENT_AMOUNT';

	/** the column name for the PAYMENT_DESCRIPTION field */
	const PAYMENT_DESCRIPTION = 'payment.PAYMENT_DESCRIPTION';

	/** the column name for the PAYMENT_CARD_TYPE field */
	const PAYMENT_CARD_TYPE = 'payment.PAYMENT_CARD_TYPE';

	/** the column name for the PAYMENT_LAST_FOUR_CC_DIGITS field */
	const PAYMENT_LAST_FOUR_CC_DIGITS = 'payment.PAYMENT_LAST_FOUR_CC_DIGITS';

	/** the column name for the PAYMENT_CVV2 field */
	const PAYMENT_CVV2 = 'payment.PAYMENT_CVV2';

	/** the column name for the PAYMENT_CC_EXP field */
	const PAYMENT_CC_EXP = 'payment.PAYMENT_CC_EXP';

	/** the column name for the PAYMENT_CREATED_AT field */
	const PAYMENT_CREATED_AT = 'payment.PAYMENT_CREATED_AT';

	/** the column name for the PAYMENT_UPDATED_AT field */
	const PAYMENT_UPDATED_AT = 'payment.PAYMENT_UPDATED_AT';

	/** the column name for the PAYMENT_IP field */
	const PAYMENT_IP = 'payment.PAYMENT_IP';

	/** the column name for the PAYMENT_SITE_ID field */
	const PAYMENT_SITE_ID = 'payment.PAYMENT_SITE_ID';

	/** the column name for the PAYMENT_TRANSACTION_ID field */
	const PAYMENT_TRANSACTION_ID = 'payment.PAYMENT_TRANSACTION_ID';

	/** the column name for the PAYMENT_FRAUD_SCORE field */
	const PAYMENT_FRAUD_SCORE = 'payment.PAYMENT_FRAUD_SCORE';

	/** the column name for the PAYMENT_MAXMIND_OBJECT field */
	const PAYMENT_MAXMIND_OBJECT = 'payment.PAYMENT_MAXMIND_OBJECT';

	/** the column name for the PAYMENT_ORDER_PROCESSOR field */
	const PAYMENT_ORDER_PROCESSOR = 'payment.PAYMENT_ORDER_PROCESSOR';

	/** the column name for the PAYMENT_INVITES field */
	const PAYMENT_INVITES = 'payment.PAYMENT_INVITES';

	/**
	 * An identiy map to hold any loaded instances of Payment objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Payment[]
	 */
	public static $instances = array();


	// symfony behavior
	
	/**
	 * Indicates whether the current model includes I18N.
	 */
	const IS_I18N = false;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('PaymentId', 'FkFilmId', 'FkScreeningId', 'FkScreeningName', 'FkAudienceId', 'FkSubscriptionId', 'FkUserId', 'PaymentUniqueCode', 'PaymentType', 'PaymentFirstName', 'PaymentLastName', 'PaymentEmail', 'PaymentBAddr1', 'PaymentBAddr2', 'PaymentBCity', 'PaymentBState', 'PaymentBZipcode', 'PaymentBCountry', 'PaymentStatus', 'PaymentAmount', 'PaymentDescription', 'PaymentCardType', 'PaymentLastFourCcDigits', 'PaymentCvv2', 'PaymentCcExp', 'PaymentCreatedAt', 'PaymentUpdatedAt', 'PaymentIp', 'PaymentSiteId', 'PaymentTransactionId', 'PaymentFraudScore', 'PaymentMaxmindObject', 'PaymentOrderProcessor', 'PaymentInvites', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('paymentId', 'fkFilmId', 'fkScreeningId', 'fkScreeningName', 'fkAudienceId', 'fkSubscriptionId', 'fkUserId', 'paymentUniqueCode', 'paymentType', 'paymentFirstName', 'paymentLastName', 'paymentEmail', 'paymentBAddr1', 'paymentBAddr2', 'paymentBCity', 'paymentBState', 'paymentBZipcode', 'paymentBCountry', 'paymentStatus', 'paymentAmount', 'paymentDescription', 'paymentCardType', 'paymentLastFourCcDigits', 'paymentCvv2', 'paymentCcExp', 'paymentCreatedAt', 'paymentUpdatedAt', 'paymentIp', 'paymentSiteId', 'paymentTransactionId', 'paymentFraudScore', 'paymentMaxmindObject', 'paymentOrderProcessor', 'paymentInvites', ),
		BasePeer::TYPE_COLNAME => array (self::PAYMENT_ID, self::FK_FILM_ID, self::FK_SCREENING_ID, self::FK_SCREENING_NAME, self::FK_AUDIENCE_ID, self::FK_SUBSCRIPTION_ID, self::FK_USER_ID, self::PAYMENT_UNIQUE_CODE, self::PAYMENT_TYPE, self::PAYMENT_FIRST_NAME, self::PAYMENT_LAST_NAME, self::PAYMENT_EMAIL, self::PAYMENT_B_ADDR_1, self::PAYMENT_B_ADDR_2, self::PAYMENT_B_CITY, self::PAYMENT_B_STATE, self::PAYMENT_B_ZIPCODE, self::PAYMENT_B_COUNTRY, self::PAYMENT_STATUS, self::PAYMENT_AMOUNT, self::PAYMENT_DESCRIPTION, self::PAYMENT_CARD_TYPE, self::PAYMENT_LAST_FOUR_CC_DIGITS, self::PAYMENT_CVV2, self::PAYMENT_CC_EXP, self::PAYMENT_CREATED_AT, self::PAYMENT_UPDATED_AT, self::PAYMENT_IP, self::PAYMENT_SITE_ID, self::PAYMENT_TRANSACTION_ID, self::PAYMENT_FRAUD_SCORE, self::PAYMENT_MAXMIND_OBJECT, self::PAYMENT_ORDER_PROCESSOR, self::PAYMENT_INVITES, ),
		BasePeer::TYPE_FIELDNAME => array ('payment_id', 'fk_film_id', 'fk_screening_id', 'fk_screening_name', 'fk_audience_id', 'fk_subscription_id', 'fk_user_id', 'payment_unique_code', 'payment_type', 'payment_first_name', 'payment_last_name', 'payment_email', 'payment_b_addr_1', 'payment_b_addr_2', 'payment_b_city', 'payment_b_state', 'payment_b_zipcode', 'payment_b_country', 'payment_status', 'payment_amount', 'payment_description', 'payment_card_type', 'payment_last_four_CC_digits', 'payment_cvv2', 'payment_cc_exp', 'payment_created_at', 'payment_updated_at', 'payment_ip', 'payment_site_id', 'payment_transaction_id', 'payment_fraud_score', 'payment_maxmind_object', 'payment_order_processor', 'payment_invites', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('PaymentId' => 0, 'FkFilmId' => 1, 'FkScreeningId' => 2, 'FkScreeningName' => 3, 'FkAudienceId' => 4, 'FkSubscriptionId' => 5, 'FkUserId' => 6, 'PaymentUniqueCode' => 7, 'PaymentType' => 8, 'PaymentFirstName' => 9, 'PaymentLastName' => 10, 'PaymentEmail' => 11, 'PaymentBAddr1' => 12, 'PaymentBAddr2' => 13, 'PaymentBCity' => 14, 'PaymentBState' => 15, 'PaymentBZipcode' => 16, 'PaymentBCountry' => 17, 'PaymentStatus' => 18, 'PaymentAmount' => 19, 'PaymentDescription' => 20, 'PaymentCardType' => 21, 'PaymentLastFourCcDigits' => 22, 'PaymentCvv2' => 23, 'PaymentCcExp' => 24, 'PaymentCreatedAt' => 25, 'PaymentUpdatedAt' => 26, 'PaymentIp' => 27, 'PaymentSiteId' => 28, 'PaymentTransactionId' => 29, 'PaymentFraudScore' => 30, 'PaymentMaxmindObject' => 31, 'PaymentOrderProcessor' => 32, 'PaymentInvites' => 33, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('paymentId' => 0, 'fkFilmId' => 1, 'fkScreeningId' => 2, 'fkScreeningName' => 3, 'fkAudienceId' => 4, 'fkSubscriptionId' => 5, 'fkUserId' => 6, 'paymentUniqueCode' => 7, 'paymentType' => 8, 'paymentFirstName' => 9, 'paymentLastName' => 10, 'paymentEmail' => 11, 'paymentBAddr1' => 12, 'paymentBAddr2' => 13, 'paymentBCity' => 14, 'paymentBState' => 15, 'paymentBZipcode' => 16, 'paymentBCountry' => 17, 'paymentStatus' => 18, 'paymentAmount' => 19, 'paymentDescription' => 20, 'paymentCardType' => 21, 'paymentLastFourCcDigits' => 22, 'paymentCvv2' => 23, 'paymentCcExp' => 24, 'paymentCreatedAt' => 25, 'paymentUpdatedAt' => 26, 'paymentIp' => 27, 'paymentSiteId' => 28, 'paymentTransactionId' => 29, 'paymentFraudScore' => 30, 'paymentMaxmindObject' => 31, 'paymentOrderProcessor' => 32, 'paymentInvites' => 33, ),
		BasePeer::TYPE_COLNAME => array (self::PAYMENT_ID => 0, self::FK_FILM_ID => 1, self::FK_SCREENING_ID => 2, self::FK_SCREENING_NAME => 3, self::FK_AUDIENCE_ID => 4, self::FK_SUBSCRIPTION_ID => 5, self::FK_USER_ID => 6, self::PAYMENT_UNIQUE_CODE => 7, self::PAYMENT_TYPE => 8, self::PAYMENT_FIRST_NAME => 9, self::PAYMENT_LAST_NAME => 10, self::PAYMENT_EMAIL => 11, self::PAYMENT_B_ADDR_1 => 12, self::PAYMENT_B_ADDR_2 => 13, self::PAYMENT_B_CITY => 14, self::PAYMENT_B_STATE => 15, self::PAYMENT_B_ZIPCODE => 16, self::PAYMENT_B_COUNTRY => 17, self::PAYMENT_STATUS => 18, self::PAYMENT_AMOUNT => 19, self::PAYMENT_DESCRIPTION => 20, self::PAYMENT_CARD_TYPE => 21, self::PAYMENT_LAST_FOUR_CC_DIGITS => 22, self::PAYMENT_CVV2 => 23, self::PAYMENT_CC_EXP => 24, self::PAYMENT_CREATED_AT => 25, self::PAYMENT_UPDATED_AT => 26, self::PAYMENT_IP => 27, self::PAYMENT_SITE_ID => 28, self::PAYMENT_TRANSACTION_ID => 29, self::PAYMENT_FRAUD_SCORE => 30, self::PAYMENT_MAXMIND_OBJECT => 31, self::PAYMENT_ORDER_PROCESSOR => 32, self::PAYMENT_INVITES => 33, ),
		BasePeer::TYPE_FIELDNAME => array ('payment_id' => 0, 'fk_film_id' => 1, 'fk_screening_id' => 2, 'fk_screening_name' => 3, 'fk_audience_id' => 4, 'fk_subscription_id' => 5, 'fk_user_id' => 6, 'payment_unique_code' => 7, 'payment_type' => 8, 'payment_first_name' => 9, 'payment_last_name' => 10, 'payment_email' => 11, 'payment_b_addr_1' => 12, 'payment_b_addr_2' => 13, 'payment_b_city' => 14, 'payment_b_state' => 15, 'payment_b_zipcode' => 16, 'payment_b_country' => 17, 'payment_status' => 18, 'payment_amount' => 19, 'payment_description' => 20, 'payment_card_type' => 21, 'payment_last_four_CC_digits' => 22, 'payment_cvv2' => 23, 'payment_cc_exp' => 24, 'payment_created_at' => 25, 'payment_updated_at' => 26, 'payment_ip' => 27, 'payment_site_id' => 28, 'payment_transaction_id' => 29, 'payment_fraud_score' => 30, 'payment_maxmind_object' => 31, 'payment_order_processor' => 32, 'payment_invites' => 33, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, )
	);

	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. PaymentPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(PaymentPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_ID);
		$criteria->addSelectColumn(PaymentPeer::FK_FILM_ID);
		$criteria->addSelectColumn(PaymentPeer::FK_SCREENING_ID);
		$criteria->addSelectColumn(PaymentPeer::FK_SCREENING_NAME);
		$criteria->addSelectColumn(PaymentPeer::FK_AUDIENCE_ID);
		$criteria->addSelectColumn(PaymentPeer::FK_SUBSCRIPTION_ID);
		$criteria->addSelectColumn(PaymentPeer::FK_USER_ID);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_UNIQUE_CODE);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_TYPE);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_FIRST_NAME);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_LAST_NAME);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_EMAIL);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_B_ADDR_1);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_B_ADDR_2);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_B_CITY);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_B_STATE);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_B_ZIPCODE);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_B_COUNTRY);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_STATUS);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_AMOUNT);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_DESCRIPTION);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_CARD_TYPE);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_LAST_FOUR_CC_DIGITS);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_CVV2);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_CC_EXP);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_CREATED_AT);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_UPDATED_AT);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_IP);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_SITE_ID);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_TRANSACTION_ID);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_FRAUD_SCORE);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_MAXMIND_OBJECT);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_ORDER_PROCESSOR);
		$criteria->addSelectColumn(PaymentPeer::PAYMENT_INVITES);
	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(PaymentPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			PaymentPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(PaymentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePaymentPeer', $criteria, $con);
		}

		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Payment
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = PaymentPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return PaymentPeer::populateObjects(PaymentPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(PaymentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			PaymentPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePaymentPeer', $criteria, $con);
		}


		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Payment $value A Payment object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Payment $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getPaymentId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Payment object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Payment) {
				$key = (string) $value->getPaymentId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Payment object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Payment Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Method to invalidate the instance pool of all tables related to payment
	 * by a foreign key with ON DELETE CASCADE
	 */
	public static function clearRelatedInstancePool()
	{
	}

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol] === null) {
			return null;
		}
		return (string) $row[$startcol];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = PaymentPeer::getOMClass(false);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = PaymentPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = PaymentPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				PaymentPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * Add a TableMap instance to the database for this peer class.
	 */
	public static function buildTableMap()
	{
	  $dbMap = Propel::getDatabaseMap(BasePaymentPeer::DATABASE_NAME);
	  if (!$dbMap->hasTable(BasePaymentPeer::TABLE_NAME))
	  {
	    $dbMap->addTableObject(new PaymentTableMap());
	  }
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * If $withPrefix is true, the returned path
	 * uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @param      boolean  Whether or not to return the path wit hthe class name 
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass($withPrefix = true)
	{
		return $withPrefix ? PaymentPeer::CLASS_DEFAULT : PaymentPeer::OM_CLASS;
	}

	/**
	 * Method perform an INSERT on the database, given a Payment or Criteria object.
	 *
	 * @param      mixed $values Criteria or Payment object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BasePaymentPeer:doInsert:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BasePaymentPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(PaymentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Payment object
		}

		if ($criteria->containsKey(PaymentPeer::PAYMENT_ID) && $criteria->keyContainsValue(PaymentPeer::PAYMENT_ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.PaymentPeer::PAYMENT_ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BasePaymentPeer:doInsert:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BasePaymentPeer', $values, $con, $pk);
    }

		return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Payment or Criteria object.
	 *
	 * @param      mixed $values Criteria or Payment object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BasePaymentPeer:doUpdate:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BasePaymentPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(PaymentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(PaymentPeer::PAYMENT_ID);
			$selectCriteria->add(PaymentPeer::PAYMENT_ID, $criteria->remove(PaymentPeer::PAYMENT_ID), $comparison);

		} else { // $values is Payment object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BasePaymentPeer:doUpdate:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BasePaymentPeer', $values, $con, $ret);
    }

    return $ret;
	}

	/**
	 * Method to DELETE all rows from the payment table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(PaymentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(PaymentPeer::TABLE_NAME, $con);
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			PaymentPeer::clearInstancePool();
			PaymentPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Payment or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Payment object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(PaymentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			PaymentPeer::clearInstancePool();
			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Payment) { // it's a model object
			// invalidate the cache for this single object
			PaymentPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else { // it's a primary key, or an array of pks
			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(PaymentPeer::PAYMENT_ID, (array) $values, Criteria::IN);
			// invalidate the cache for this object(s)
			foreach ((array) $values as $singleval) {
				PaymentPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);
			PaymentPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given Payment object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Payment $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Payment $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(PaymentPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(PaymentPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		return BasePeer::doValidate(PaymentPeer::DATABASE_NAME, PaymentPeer::TABLE_NAME, $columns);
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Payment
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = PaymentPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(PaymentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(PaymentPeer::DATABASE_NAME);
		$criteria->add(PaymentPeer::PAYMENT_ID, $pk);

		$v = PaymentPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(PaymentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(PaymentPeer::DATABASE_NAME);
			$criteria->add(PaymentPeer::PAYMENT_ID, $pks, Criteria::IN);
			$objs = PaymentPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

	// symfony behavior
	
	/**
	 * Returns an array of arrays that contain columns in each unique index.
	 *
	 * @return array
	 */
	static public function getUniqueColumnNames()
	{
	  return array();
	}

	// symfony_behaviors behavior
	
	/**
	 * Returns the name of the hook to call from inside the supplied method.
	 *
	 * @param string $method The calling method
	 *
	 * @return string A hook name for {@link sfMixer}
	 *
	 * @throws LogicException If the method name is not recognized
	 */
	static private function getMixerPreSelectHook($method)
	{
	  if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
	  {
	    return sprintf('BasePaymentPeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
	  }
	
	  throw new LogicException(sprintf('Unrecognized function "%s"', $method));
	}

} // BasePaymentPeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BasePaymentPeer::buildTableMap();

