<?php

/**
 * Base class that represents a row from the 'conversation' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu 26 Apr 2012 01:25:32 PM EDT
 *
 * @package    lib.model.om
 */
abstract class BaseConversation extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ConversationPeer
	 */
	protected static $peer;

	/**
	 * The value for the conversation_id field.
	 * @var        int
	 */
	protected $conversation_id;

	/**
	 * The value for the conversation_author field.
	 * @var        string
	 */
	protected $conversation_author;

	/**
	 * The value for the conversation_author_image field.
	 * @var        string
	 */
	protected $conversation_author_image;

	/**
	 * The value for the fk_author_id field.
	 * @var        int
	 */
	protected $fk_author_id;

	/**
	 * The value for the fk_film_id field.
	 * @var        int
	 */
	protected $fk_film_id;

	/**
	 * The value for the conversation_date_created field.
	 * @var        string
	 */
	protected $conversation_date_created;

	/**
	 * The value for the conversation_sequence field.
	 * @var        int
	 */
	protected $conversation_sequence;

	/**
	 * The value for the conversation_thread field.
	 * @var        string
	 */
	protected $conversation_thread;

	/**
	 * The value for the conversation_body field.
	 * @var        string
	 */
	protected $conversation_body;

	/**
	 * The value for the conversation_rating field.
	 * @var        int
	 */
	protected $conversation_rating;

	/**
	 * The value for the conversation_status field.
	 * @var        int
	 */
	protected $conversation_status;

	/**
	 * The value for the conversation_guid field.
	 * @var        string
	 */
	protected $conversation_guid;

	/**
	 * The value for the fk_promoter_id field.
	 * @var        int
	 */
	protected $fk_promoter_id;

	/**
	 * The value for the conversation_asset_type field.
	 * @var        string
	 */
	protected $conversation_asset_type;

	/**
	 * The value for the conversation_asset_guid field.
	 * @var        string
	 */
	protected $conversation_asset_guid;

	/**
	 * The value for the fk_screening_id field.
	 * @var        int
	 */
	protected $fk_screening_id;

	/**
	 * The value for the fk_user_id field.
	 * @var        int
	 */
	protected $fk_user_id;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'ConversationPeer';

	/**
	 * Get the [conversation_id] column value.
	 * 
	 * @return     int
	 */
	public function getConversationId()
	{
		return $this->conversation_id;
	}

	/**
	 * Get the [conversation_author] column value.
	 * 
	 * @return     string
	 */
	public function getConversationAuthor()
	{
		return $this->conversation_author;
	}

	/**
	 * Get the [conversation_author_image] column value.
	 * 
	 * @return     string
	 */
	public function getConversationAuthorImage()
	{
		return $this->conversation_author_image;
	}

	/**
	 * Get the [fk_author_id] column value.
	 * 
	 * @return     int
	 */
	public function getFkAuthorId()
	{
		return $this->fk_author_id;
	}

	/**
	 * Get the [fk_film_id] column value.
	 * 
	 * @return     int
	 */
	public function getFkFilmId()
	{
		return $this->fk_film_id;
	}

	/**
	 * Get the [optionally formatted] temporal [conversation_date_created] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getConversationDateCreated($format = 'Y-m-d H:i:s')
	{
		if ($this->conversation_date_created === null) {
			return null;
		}


		if ($this->conversation_date_created === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->conversation_date_created);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->conversation_date_created, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [conversation_sequence] column value.
	 * 
	 * @return     int
	 */
	public function getConversationSequence()
	{
		return $this->conversation_sequence;
	}

	/**
	 * Get the [conversation_thread] column value.
	 * 
	 * @return     string
	 */
	public function getConversationThread()
	{
		return $this->conversation_thread;
	}

	/**
	 * Get the [conversation_body] column value.
	 * 
	 * @return     string
	 */
	public function getConversationBody()
	{
		return $this->conversation_body;
	}

	/**
	 * Get the [conversation_rating] column value.
	 * 
	 * @return     int
	 */
	public function getConversationRating()
	{
		return $this->conversation_rating;
	}

	/**
	 * Get the [conversation_status] column value.
	 * 
	 * @return     int
	 */
	public function getConversationStatus()
	{
		return $this->conversation_status;
	}

	/**
	 * Get the [conversation_guid] column value.
	 * 
	 * @return     string
	 */
	public function getConversationGuid()
	{
		return $this->conversation_guid;
	}

	/**
	 * Get the [fk_promoter_id] column value.
	 * 
	 * @return     int
	 */
	public function getFkPromoterId()
	{
		return $this->fk_promoter_id;
	}

	/**
	 * Get the [conversation_asset_type] column value.
	 * 
	 * @return     string
	 */
	public function getConversationAssetType()
	{
		return $this->conversation_asset_type;
	}

	/**
	 * Get the [conversation_asset_guid] column value.
	 * 
	 * @return     string
	 */
	public function getConversationAssetGuid()
	{
		return $this->conversation_asset_guid;
	}

	/**
	 * Get the [fk_screening_id] column value.
	 * 
	 * @return     int
	 */
	public function getFkScreeningId()
	{
		return $this->fk_screening_id;
	}

	/**
	 * Get the [fk_user_id] column value.
	 * 
	 * @return     int
	 */
	public function getFkUserId()
	{
		return $this->fk_user_id;
	}

	/**
	 * Set the value of [conversation_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Conversation The current object (for fluent API support)
	 */
	public function setConversationId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->conversation_id !== $v) {
			$this->conversation_id = $v;
			$this->modifiedColumns[] = ConversationPeer::CONVERSATION_ID;
		}

		return $this;
	} // setConversationId()

	/**
	 * Set the value of [conversation_author] column.
	 * 
	 * @param      string $v new value
	 * @return     Conversation The current object (for fluent API support)
	 */
	public function setConversationAuthor($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->conversation_author !== $v) {
			$this->conversation_author = $v;
			$this->modifiedColumns[] = ConversationPeer::CONVERSATION_AUTHOR;
		}

		return $this;
	} // setConversationAuthor()

	/**
	 * Set the value of [conversation_author_image] column.
	 * 
	 * @param      string $v new value
	 * @return     Conversation The current object (for fluent API support)
	 */
	public function setConversationAuthorImage($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->conversation_author_image !== $v) {
			$this->conversation_author_image = $v;
			$this->modifiedColumns[] = ConversationPeer::CONVERSATION_AUTHOR_IMAGE;
		}

		return $this;
	} // setConversationAuthorImage()

	/**
	 * Set the value of [fk_author_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Conversation The current object (for fluent API support)
	 */
	public function setFkAuthorId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->fk_author_id !== $v) {
			$this->fk_author_id = $v;
			$this->modifiedColumns[] = ConversationPeer::FK_AUTHOR_ID;
		}

		return $this;
	} // setFkAuthorId()

	/**
	 * Set the value of [fk_film_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Conversation The current object (for fluent API support)
	 */
	public function setFkFilmId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->fk_film_id !== $v) {
			$this->fk_film_id = $v;
			$this->modifiedColumns[] = ConversationPeer::FK_FILM_ID;
		}

		return $this;
	} // setFkFilmId()

	/**
	 * Sets the value of [conversation_date_created] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Conversation The current object (for fluent API support)
	 */
	public function setConversationDateCreated($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->conversation_date_created !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->conversation_date_created !== null && $tmpDt = new DateTime($this->conversation_date_created)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->conversation_date_created = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = ConversationPeer::CONVERSATION_DATE_CREATED;
			}
		} // if either are not null

		return $this;
	} // setConversationDateCreated()

	/**
	 * Set the value of [conversation_sequence] column.
	 * 
	 * @param      int $v new value
	 * @return     Conversation The current object (for fluent API support)
	 */
	public function setConversationSequence($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->conversation_sequence !== $v) {
			$this->conversation_sequence = $v;
			$this->modifiedColumns[] = ConversationPeer::CONVERSATION_SEQUENCE;
		}

		return $this;
	} // setConversationSequence()

	/**
	 * Set the value of [conversation_thread] column.
	 * 
	 * @param      string $v new value
	 * @return     Conversation The current object (for fluent API support)
	 */
	public function setConversationThread($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->conversation_thread !== $v) {
			$this->conversation_thread = $v;
			$this->modifiedColumns[] = ConversationPeer::CONVERSATION_THREAD;
		}

		return $this;
	} // setConversationThread()

	/**
	 * Set the value of [conversation_body] column.
	 * 
	 * @param      string $v new value
	 * @return     Conversation The current object (for fluent API support)
	 */
	public function setConversationBody($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->conversation_body !== $v) {
			$this->conversation_body = $v;
			$this->modifiedColumns[] = ConversationPeer::CONVERSATION_BODY;
		}

		return $this;
	} // setConversationBody()

	/**
	 * Set the value of [conversation_rating] column.
	 * 
	 * @param      int $v new value
	 * @return     Conversation The current object (for fluent API support)
	 */
	public function setConversationRating($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->conversation_rating !== $v) {
			$this->conversation_rating = $v;
			$this->modifiedColumns[] = ConversationPeer::CONVERSATION_RATING;
		}

		return $this;
	} // setConversationRating()

	/**
	 * Set the value of [conversation_status] column.
	 * 
	 * @param      int $v new value
	 * @return     Conversation The current object (for fluent API support)
	 */
	public function setConversationStatus($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->conversation_status !== $v) {
			$this->conversation_status = $v;
			$this->modifiedColumns[] = ConversationPeer::CONVERSATION_STATUS;
		}

		return $this;
	} // setConversationStatus()

	/**
	 * Set the value of [conversation_guid] column.
	 * 
	 * @param      string $v new value
	 * @return     Conversation The current object (for fluent API support)
	 */
	public function setConversationGuid($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->conversation_guid !== $v) {
			$this->conversation_guid = $v;
			$this->modifiedColumns[] = ConversationPeer::CONVERSATION_GUID;
		}

		return $this;
	} // setConversationGuid()

	/**
	 * Set the value of [fk_promoter_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Conversation The current object (for fluent API support)
	 */
	public function setFkPromoterId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->fk_promoter_id !== $v) {
			$this->fk_promoter_id = $v;
			$this->modifiedColumns[] = ConversationPeer::FK_PROMOTER_ID;
		}

		return $this;
	} // setFkPromoterId()

	/**
	 * Set the value of [conversation_asset_type] column.
	 * 
	 * @param      string $v new value
	 * @return     Conversation The current object (for fluent API support)
	 */
	public function setConversationAssetType($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->conversation_asset_type !== $v) {
			$this->conversation_asset_type = $v;
			$this->modifiedColumns[] = ConversationPeer::CONVERSATION_ASSET_TYPE;
		}

		return $this;
	} // setConversationAssetType()

	/**
	 * Set the value of [conversation_asset_guid] column.
	 * 
	 * @param      string $v new value
	 * @return     Conversation The current object (for fluent API support)
	 */
	public function setConversationAssetGuid($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->conversation_asset_guid !== $v) {
			$this->conversation_asset_guid = $v;
			$this->modifiedColumns[] = ConversationPeer::CONVERSATION_ASSET_GUID;
		}

		return $this;
	} // setConversationAssetGuid()

	/**
	 * Set the value of [fk_screening_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Conversation The current object (for fluent API support)
	 */
	public function setFkScreeningId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->fk_screening_id !== $v) {
			$this->fk_screening_id = $v;
			$this->modifiedColumns[] = ConversationPeer::FK_SCREENING_ID;
		}

		return $this;
	} // setFkScreeningId()

	/**
	 * Set the value of [fk_user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Conversation The current object (for fluent API support)
	 */
	public function setFkUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->fk_user_id !== $v) {
			$this->fk_user_id = $v;
			$this->modifiedColumns[] = ConversationPeer::FK_USER_ID;
		}

		return $this;
	} // setFkUserId()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->conversation_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->conversation_author = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->conversation_author_image = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->fk_author_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->fk_film_id = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->conversation_date_created = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->conversation_sequence = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->conversation_thread = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->conversation_body = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->conversation_rating = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->conversation_status = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
			$this->conversation_guid = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->fk_promoter_id = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->conversation_asset_type = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->conversation_asset_guid = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->fk_screening_id = ($row[$startcol + 15] !== null) ? (int) $row[$startcol + 15] : null;
			$this->fk_user_id = ($row[$startcol + 16] !== null) ? (int) $row[$startcol + 16] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 17; // 17 = ConversationPeer::NUM_COLUMNS - ConversationPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Conversation object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ConversationPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ConversationPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ConversationPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseConversation:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				ConversationPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseConversation:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ConversationPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseConversation:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseConversation:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				ConversationPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ConversationPeer::CONVERSATION_ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ConversationPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setConversationId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ConversationPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = ConversationPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ConversationPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getConversationId();
				break;
			case 1:
				return $this->getConversationAuthor();
				break;
			case 2:
				return $this->getConversationAuthorImage();
				break;
			case 3:
				return $this->getFkAuthorId();
				break;
			case 4:
				return $this->getFkFilmId();
				break;
			case 5:
				return $this->getConversationDateCreated();
				break;
			case 6:
				return $this->getConversationSequence();
				break;
			case 7:
				return $this->getConversationThread();
				break;
			case 8:
				return $this->getConversationBody();
				break;
			case 9:
				return $this->getConversationRating();
				break;
			case 10:
				return $this->getConversationStatus();
				break;
			case 11:
				return $this->getConversationGuid();
				break;
			case 12:
				return $this->getFkPromoterId();
				break;
			case 13:
				return $this->getConversationAssetType();
				break;
			case 14:
				return $this->getConversationAssetGuid();
				break;
			case 15:
				return $this->getFkScreeningId();
				break;
			case 16:
				return $this->getFkUserId();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ConversationPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getConversationId(),
			$keys[1] => $this->getConversationAuthor(),
			$keys[2] => $this->getConversationAuthorImage(),
			$keys[3] => $this->getFkAuthorId(),
			$keys[4] => $this->getFkFilmId(),
			$keys[5] => $this->getConversationDateCreated(),
			$keys[6] => $this->getConversationSequence(),
			$keys[7] => $this->getConversationThread(),
			$keys[8] => $this->getConversationBody(),
			$keys[9] => $this->getConversationRating(),
			$keys[10] => $this->getConversationStatus(),
			$keys[11] => $this->getConversationGuid(),
			$keys[12] => $this->getFkPromoterId(),
			$keys[13] => $this->getConversationAssetType(),
			$keys[14] => $this->getConversationAssetGuid(),
			$keys[15] => $this->getFkScreeningId(),
			$keys[16] => $this->getFkUserId(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ConversationPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setConversationId($value);
				break;
			case 1:
				$this->setConversationAuthor($value);
				break;
			case 2:
				$this->setConversationAuthorImage($value);
				break;
			case 3:
				$this->setFkAuthorId($value);
				break;
			case 4:
				$this->setFkFilmId($value);
				break;
			case 5:
				$this->setConversationDateCreated($value);
				break;
			case 6:
				$this->setConversationSequence($value);
				break;
			case 7:
				$this->setConversationThread($value);
				break;
			case 8:
				$this->setConversationBody($value);
				break;
			case 9:
				$this->setConversationRating($value);
				break;
			case 10:
				$this->setConversationStatus($value);
				break;
			case 11:
				$this->setConversationGuid($value);
				break;
			case 12:
				$this->setFkPromoterId($value);
				break;
			case 13:
				$this->setConversationAssetType($value);
				break;
			case 14:
				$this->setConversationAssetGuid($value);
				break;
			case 15:
				$this->setFkScreeningId($value);
				break;
			case 16:
				$this->setFkUserId($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ConversationPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setConversationId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setConversationAuthor($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setConversationAuthorImage($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setFkAuthorId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setFkFilmId($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setConversationDateCreated($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setConversationSequence($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setConversationThread($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setConversationBody($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setConversationRating($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setConversationStatus($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setConversationGuid($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setFkPromoterId($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setConversationAssetType($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setConversationAssetGuid($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setFkScreeningId($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setFkUserId($arr[$keys[16]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ConversationPeer::DATABASE_NAME);

		if ($this->isColumnModified(ConversationPeer::CONVERSATION_ID)) $criteria->add(ConversationPeer::CONVERSATION_ID, $this->conversation_id);
		if ($this->isColumnModified(ConversationPeer::CONVERSATION_AUTHOR)) $criteria->add(ConversationPeer::CONVERSATION_AUTHOR, $this->conversation_author);
		if ($this->isColumnModified(ConversationPeer::CONVERSATION_AUTHOR_IMAGE)) $criteria->add(ConversationPeer::CONVERSATION_AUTHOR_IMAGE, $this->conversation_author_image);
		if ($this->isColumnModified(ConversationPeer::FK_AUTHOR_ID)) $criteria->add(ConversationPeer::FK_AUTHOR_ID, $this->fk_author_id);
		if ($this->isColumnModified(ConversationPeer::FK_FILM_ID)) $criteria->add(ConversationPeer::FK_FILM_ID, $this->fk_film_id);
		if ($this->isColumnModified(ConversationPeer::CONVERSATION_DATE_CREATED)) $criteria->add(ConversationPeer::CONVERSATION_DATE_CREATED, $this->conversation_date_created);
		if ($this->isColumnModified(ConversationPeer::CONVERSATION_SEQUENCE)) $criteria->add(ConversationPeer::CONVERSATION_SEQUENCE, $this->conversation_sequence);
		if ($this->isColumnModified(ConversationPeer::CONVERSATION_THREAD)) $criteria->add(ConversationPeer::CONVERSATION_THREAD, $this->conversation_thread);
		if ($this->isColumnModified(ConversationPeer::CONVERSATION_BODY)) $criteria->add(ConversationPeer::CONVERSATION_BODY, $this->conversation_body);
		if ($this->isColumnModified(ConversationPeer::CONVERSATION_RATING)) $criteria->add(ConversationPeer::CONVERSATION_RATING, $this->conversation_rating);
		if ($this->isColumnModified(ConversationPeer::CONVERSATION_STATUS)) $criteria->add(ConversationPeer::CONVERSATION_STATUS, $this->conversation_status);
		if ($this->isColumnModified(ConversationPeer::CONVERSATION_GUID)) $criteria->add(ConversationPeer::CONVERSATION_GUID, $this->conversation_guid);
		if ($this->isColumnModified(ConversationPeer::FK_PROMOTER_ID)) $criteria->add(ConversationPeer::FK_PROMOTER_ID, $this->fk_promoter_id);
		if ($this->isColumnModified(ConversationPeer::CONVERSATION_ASSET_TYPE)) $criteria->add(ConversationPeer::CONVERSATION_ASSET_TYPE, $this->conversation_asset_type);
		if ($this->isColumnModified(ConversationPeer::CONVERSATION_ASSET_GUID)) $criteria->add(ConversationPeer::CONVERSATION_ASSET_GUID, $this->conversation_asset_guid);
		if ($this->isColumnModified(ConversationPeer::FK_SCREENING_ID)) $criteria->add(ConversationPeer::FK_SCREENING_ID, $this->fk_screening_id);
		if ($this->isColumnModified(ConversationPeer::FK_USER_ID)) $criteria->add(ConversationPeer::FK_USER_ID, $this->fk_user_id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ConversationPeer::DATABASE_NAME);

		$criteria->add(ConversationPeer::CONVERSATION_ID, $this->conversation_id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getConversationId();
	}

	/**
	 * Generic method to set the primary key (conversation_id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setConversationId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Conversation (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setConversationAuthor($this->conversation_author);

		$copyObj->setConversationAuthorImage($this->conversation_author_image);

		$copyObj->setFkAuthorId($this->fk_author_id);

		$copyObj->setFkFilmId($this->fk_film_id);

		$copyObj->setConversationDateCreated($this->conversation_date_created);

		$copyObj->setConversationSequence($this->conversation_sequence);

		$copyObj->setConversationThread($this->conversation_thread);

		$copyObj->setConversationBody($this->conversation_body);

		$copyObj->setConversationRating($this->conversation_rating);

		$copyObj->setConversationStatus($this->conversation_status);

		$copyObj->setConversationGuid($this->conversation_guid);

		$copyObj->setFkPromoterId($this->fk_promoter_id);

		$copyObj->setConversationAssetType($this->conversation_asset_type);

		$copyObj->setConversationAssetGuid($this->conversation_asset_guid);

		$copyObj->setFkScreeningId($this->fk_screening_id);

		$copyObj->setFkUserId($this->fk_user_id);


		$copyObj->setNew(true);

		$copyObj->setConversationId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Conversation Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ConversationPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ConversationPeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseConversation:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseConversation::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseConversation
