<?php

/**
 * Base class that represents a row from the 'wtvr_message' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu 26 Apr 2012 01:25:36 PM EDT
 *
 * @package    lib.model.om
 */
abstract class BaseWtvrMessage extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        WtvrMessagePeer
	 */
	protected static $peer;

	/**
	 * The value for the wtvr_message_id field.
	 * @var        int
	 */
	protected $wtvr_message_id;

	/**
	 * The value for the wtvr_message_identifier field.
	 * @var        string
	 */
	protected $wtvr_message_identifier;

	/**
	 * The value for the wtvr_message_scope field.
	 * Note: this column has a database default value of: 'mails'
	 * @var        string
	 */
	protected $wtvr_message_scope;

	/**
	 * The value for the wtvr_message_send_user_id field.
	 * @var        int
	 */
	protected $wtvr_message_send_user_id;

	/**
	 * The value for the wtvr_message_send_email field.
	 * @var        string
	 */
	protected $wtvr_message_send_email;

	/**
	 * The value for the wtvr_message_send_fname field.
	 * @var        string
	 */
	protected $wtvr_message_send_fname;

	/**
	 * The value for the wtvr_message_send_lname field.
	 * @var        string
	 */
	protected $wtvr_message_send_lname;

	/**
	 * The value for the wtvr_message_subject field.
	 * @var        string
	 */
	protected $wtvr_message_subject;

	/**
	 * The value for the wtvr_message_body field.
	 * @var        string
	 */
	protected $wtvr_message_body;

	/**
	 * The value for the wtvr_message_text field.
	 * @var        string
	 */
	protected $wtvr_message_text;

	/**
	 * The value for the wtvr_message_date field.
	 * @var        string
	 */
	protected $wtvr_message_date;

	/**
	 * The value for the wtvr_message_template field.
	 * @var        string
	 */
	protected $wtvr_message_template;

	/**
	 * The value for the wtvr_message_key1 field.
	 * @var        int
	 */
	protected $wtvr_message_key1;

	/**
	 * The value for the wtvr_message_key2 field.
	 * @var        int
	 */
	protected $wtvr_message_key2;

	/**
	 * The value for the wtvr_message_key3 field.
	 * @var        int
	 */
	protected $wtvr_message_key3;

	/**
	 * The value for the wtvr_message_key4 field.
	 * @var        int
	 */
	protected $wtvr_message_key4;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'WtvrMessagePeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->wtvr_message_scope = 'mails';
	}

	/**
	 * Initializes internal state of BaseWtvrMessage object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [wtvr_message_id] column value.
	 * 
	 * @return     int
	 */
	public function getWtvrMessageId()
	{
		return $this->wtvr_message_id;
	}

	/**
	 * Get the [wtvr_message_identifier] column value.
	 * 
	 * @return     string
	 */
	public function getWtvrMessageIdentifier()
	{
		return $this->wtvr_message_identifier;
	}

	/**
	 * Get the [wtvr_message_scope] column value.
	 * 
	 * @return     string
	 */
	public function getWtvrMessageScope()
	{
		return $this->wtvr_message_scope;
	}

	/**
	 * Get the [wtvr_message_send_user_id] column value.
	 * 
	 * @return     int
	 */
	public function getWtvrMessageSendUserId()
	{
		return $this->wtvr_message_send_user_id;
	}

	/**
	 * Get the [wtvr_message_send_email] column value.
	 * 
	 * @return     string
	 */
	public function getWtvrMessageSendEmail()
	{
		return $this->wtvr_message_send_email;
	}

	/**
	 * Get the [wtvr_message_send_fname] column value.
	 * 
	 * @return     string
	 */
	public function getWtvrMessageSendFname()
	{
		return $this->wtvr_message_send_fname;
	}

	/**
	 * Get the [wtvr_message_send_lname] column value.
	 * 
	 * @return     string
	 */
	public function getWtvrMessageSendLname()
	{
		return $this->wtvr_message_send_lname;
	}

	/**
	 * Get the [wtvr_message_subject] column value.
	 * 
	 * @return     string
	 */
	public function getWtvrMessageSubject()
	{
		return $this->wtvr_message_subject;
	}

	/**
	 * Get the [wtvr_message_body] column value.
	 * 
	 * @return     string
	 */
	public function getWtvrMessageBody()
	{
		return $this->wtvr_message_body;
	}

	/**
	 * Get the [wtvr_message_text] column value.
	 * 
	 * @return     string
	 */
	public function getWtvrMessageText()
	{
		return $this->wtvr_message_text;
	}

	/**
	 * Get the [optionally formatted] temporal [wtvr_message_date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getWtvrMessageDate($format = 'Y-m-d H:i:s')
	{
		if ($this->wtvr_message_date === null) {
			return null;
		}


		if ($this->wtvr_message_date === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->wtvr_message_date);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->wtvr_message_date, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [wtvr_message_template] column value.
	 * 
	 * @return     string
	 */
	public function getWtvrMessageTemplate()
	{
		return $this->wtvr_message_template;
	}

	/**
	 * Get the [wtvr_message_key1] column value.
	 * 
	 * @return     int
	 */
	public function getWtvrMessageKey1()
	{
		return $this->wtvr_message_key1;
	}

	/**
	 * Get the [wtvr_message_key2] column value.
	 * 
	 * @return     int
	 */
	public function getWtvrMessageKey2()
	{
		return $this->wtvr_message_key2;
	}

	/**
	 * Get the [wtvr_message_key3] column value.
	 * 
	 * @return     int
	 */
	public function getWtvrMessageKey3()
	{
		return $this->wtvr_message_key3;
	}

	/**
	 * Get the [wtvr_message_key4] column value.
	 * 
	 * @return     int
	 */
	public function getWtvrMessageKey4()
	{
		return $this->wtvr_message_key4;
	}

	/**
	 * Set the value of [wtvr_message_id] column.
	 * 
	 * @param      int $v new value
	 * @return     WtvrMessage The current object (for fluent API support)
	 */
	public function setWtvrMessageId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->wtvr_message_id !== $v) {
			$this->wtvr_message_id = $v;
			$this->modifiedColumns[] = WtvrMessagePeer::WTVR_MESSAGE_ID;
		}

		return $this;
	} // setWtvrMessageId()

	/**
	 * Set the value of [wtvr_message_identifier] column.
	 * 
	 * @param      string $v new value
	 * @return     WtvrMessage The current object (for fluent API support)
	 */
	public function setWtvrMessageIdentifier($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->wtvr_message_identifier !== $v) {
			$this->wtvr_message_identifier = $v;
			$this->modifiedColumns[] = WtvrMessagePeer::WTVR_MESSAGE_IDENTIFIER;
		}

		return $this;
	} // setWtvrMessageIdentifier()

	/**
	 * Set the value of [wtvr_message_scope] column.
	 * 
	 * @param      string $v new value
	 * @return     WtvrMessage The current object (for fluent API support)
	 */
	public function setWtvrMessageScope($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->wtvr_message_scope !== $v || $this->isNew()) {
			$this->wtvr_message_scope = $v;
			$this->modifiedColumns[] = WtvrMessagePeer::WTVR_MESSAGE_SCOPE;
		}

		return $this;
	} // setWtvrMessageScope()

	/**
	 * Set the value of [wtvr_message_send_user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     WtvrMessage The current object (for fluent API support)
	 */
	public function setWtvrMessageSendUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->wtvr_message_send_user_id !== $v) {
			$this->wtvr_message_send_user_id = $v;
			$this->modifiedColumns[] = WtvrMessagePeer::WTVR_MESSAGE_SEND_USER_ID;
		}

		return $this;
	} // setWtvrMessageSendUserId()

	/**
	 * Set the value of [wtvr_message_send_email] column.
	 * 
	 * @param      string $v new value
	 * @return     WtvrMessage The current object (for fluent API support)
	 */
	public function setWtvrMessageSendEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->wtvr_message_send_email !== $v) {
			$this->wtvr_message_send_email = $v;
			$this->modifiedColumns[] = WtvrMessagePeer::WTVR_MESSAGE_SEND_EMAIL;
		}

		return $this;
	} // setWtvrMessageSendEmail()

	/**
	 * Set the value of [wtvr_message_send_fname] column.
	 * 
	 * @param      string $v new value
	 * @return     WtvrMessage The current object (for fluent API support)
	 */
	public function setWtvrMessageSendFname($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->wtvr_message_send_fname !== $v) {
			$this->wtvr_message_send_fname = $v;
			$this->modifiedColumns[] = WtvrMessagePeer::WTVR_MESSAGE_SEND_FNAME;
		}

		return $this;
	} // setWtvrMessageSendFname()

	/**
	 * Set the value of [wtvr_message_send_lname] column.
	 * 
	 * @param      string $v new value
	 * @return     WtvrMessage The current object (for fluent API support)
	 */
	public function setWtvrMessageSendLname($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->wtvr_message_send_lname !== $v) {
			$this->wtvr_message_send_lname = $v;
			$this->modifiedColumns[] = WtvrMessagePeer::WTVR_MESSAGE_SEND_LNAME;
		}

		return $this;
	} // setWtvrMessageSendLname()

	/**
	 * Set the value of [wtvr_message_subject] column.
	 * 
	 * @param      string $v new value
	 * @return     WtvrMessage The current object (for fluent API support)
	 */
	public function setWtvrMessageSubject($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->wtvr_message_subject !== $v) {
			$this->wtvr_message_subject = $v;
			$this->modifiedColumns[] = WtvrMessagePeer::WTVR_MESSAGE_SUBJECT;
		}

		return $this;
	} // setWtvrMessageSubject()

	/**
	 * Set the value of [wtvr_message_body] column.
	 * 
	 * @param      string $v new value
	 * @return     WtvrMessage The current object (for fluent API support)
	 */
	public function setWtvrMessageBody($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->wtvr_message_body !== $v) {
			$this->wtvr_message_body = $v;
			$this->modifiedColumns[] = WtvrMessagePeer::WTVR_MESSAGE_BODY;
		}

		return $this;
	} // setWtvrMessageBody()

	/**
	 * Set the value of [wtvr_message_text] column.
	 * 
	 * @param      string $v new value
	 * @return     WtvrMessage The current object (for fluent API support)
	 */
	public function setWtvrMessageText($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->wtvr_message_text !== $v) {
			$this->wtvr_message_text = $v;
			$this->modifiedColumns[] = WtvrMessagePeer::WTVR_MESSAGE_TEXT;
		}

		return $this;
	} // setWtvrMessageText()

	/**
	 * Sets the value of [wtvr_message_date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     WtvrMessage The current object (for fluent API support)
	 */
	public function setWtvrMessageDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->wtvr_message_date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->wtvr_message_date !== null && $tmpDt = new DateTime($this->wtvr_message_date)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->wtvr_message_date = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = WtvrMessagePeer::WTVR_MESSAGE_DATE;
			}
		} // if either are not null

		return $this;
	} // setWtvrMessageDate()

	/**
	 * Set the value of [wtvr_message_template] column.
	 * 
	 * @param      string $v new value
	 * @return     WtvrMessage The current object (for fluent API support)
	 */
	public function setWtvrMessageTemplate($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->wtvr_message_template !== $v) {
			$this->wtvr_message_template = $v;
			$this->modifiedColumns[] = WtvrMessagePeer::WTVR_MESSAGE_TEMPLATE;
		}

		return $this;
	} // setWtvrMessageTemplate()

	/**
	 * Set the value of [wtvr_message_key1] column.
	 * 
	 * @param      int $v new value
	 * @return     WtvrMessage The current object (for fluent API support)
	 */
	public function setWtvrMessageKey1($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->wtvr_message_key1 !== $v) {
			$this->wtvr_message_key1 = $v;
			$this->modifiedColumns[] = WtvrMessagePeer::WTVR_MESSAGE_KEY1;
		}

		return $this;
	} // setWtvrMessageKey1()

	/**
	 * Set the value of [wtvr_message_key2] column.
	 * 
	 * @param      int $v new value
	 * @return     WtvrMessage The current object (for fluent API support)
	 */
	public function setWtvrMessageKey2($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->wtvr_message_key2 !== $v) {
			$this->wtvr_message_key2 = $v;
			$this->modifiedColumns[] = WtvrMessagePeer::WTVR_MESSAGE_KEY2;
		}

		return $this;
	} // setWtvrMessageKey2()

	/**
	 * Set the value of [wtvr_message_key3] column.
	 * 
	 * @param      int $v new value
	 * @return     WtvrMessage The current object (for fluent API support)
	 */
	public function setWtvrMessageKey3($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->wtvr_message_key3 !== $v) {
			$this->wtvr_message_key3 = $v;
			$this->modifiedColumns[] = WtvrMessagePeer::WTVR_MESSAGE_KEY3;
		}

		return $this;
	} // setWtvrMessageKey3()

	/**
	 * Set the value of [wtvr_message_key4] column.
	 * 
	 * @param      int $v new value
	 * @return     WtvrMessage The current object (for fluent API support)
	 */
	public function setWtvrMessageKey4($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->wtvr_message_key4 !== $v) {
			$this->wtvr_message_key4 = $v;
			$this->modifiedColumns[] = WtvrMessagePeer::WTVR_MESSAGE_KEY4;
		}

		return $this;
	} // setWtvrMessageKey4()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->wtvr_message_scope !== 'mails') {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->wtvr_message_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->wtvr_message_identifier = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->wtvr_message_scope = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->wtvr_message_send_user_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->wtvr_message_send_email = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->wtvr_message_send_fname = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->wtvr_message_send_lname = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->wtvr_message_subject = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->wtvr_message_body = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->wtvr_message_text = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->wtvr_message_date = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->wtvr_message_template = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->wtvr_message_key1 = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->wtvr_message_key2 = ($row[$startcol + 13] !== null) ? (int) $row[$startcol + 13] : null;
			$this->wtvr_message_key3 = ($row[$startcol + 14] !== null) ? (int) $row[$startcol + 14] : null;
			$this->wtvr_message_key4 = ($row[$startcol + 15] !== null) ? (int) $row[$startcol + 15] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 16; // 16 = WtvrMessagePeer::NUM_COLUMNS - WtvrMessagePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating WtvrMessage object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(WtvrMessagePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = WtvrMessagePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(WtvrMessagePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseWtvrMessage:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				WtvrMessagePeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseWtvrMessage:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(WtvrMessagePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseWtvrMessage:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseWtvrMessage:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				WtvrMessagePeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = WtvrMessagePeer::WTVR_MESSAGE_ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = WtvrMessagePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setWtvrMessageId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += WtvrMessagePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = WtvrMessagePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = WtvrMessagePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getWtvrMessageId();
				break;
			case 1:
				return $this->getWtvrMessageIdentifier();
				break;
			case 2:
				return $this->getWtvrMessageScope();
				break;
			case 3:
				return $this->getWtvrMessageSendUserId();
				break;
			case 4:
				return $this->getWtvrMessageSendEmail();
				break;
			case 5:
				return $this->getWtvrMessageSendFname();
				break;
			case 6:
				return $this->getWtvrMessageSendLname();
				break;
			case 7:
				return $this->getWtvrMessageSubject();
				break;
			case 8:
				return $this->getWtvrMessageBody();
				break;
			case 9:
				return $this->getWtvrMessageText();
				break;
			case 10:
				return $this->getWtvrMessageDate();
				break;
			case 11:
				return $this->getWtvrMessageTemplate();
				break;
			case 12:
				return $this->getWtvrMessageKey1();
				break;
			case 13:
				return $this->getWtvrMessageKey2();
				break;
			case 14:
				return $this->getWtvrMessageKey3();
				break;
			case 15:
				return $this->getWtvrMessageKey4();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = WtvrMessagePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getWtvrMessageId(),
			$keys[1] => $this->getWtvrMessageIdentifier(),
			$keys[2] => $this->getWtvrMessageScope(),
			$keys[3] => $this->getWtvrMessageSendUserId(),
			$keys[4] => $this->getWtvrMessageSendEmail(),
			$keys[5] => $this->getWtvrMessageSendFname(),
			$keys[6] => $this->getWtvrMessageSendLname(),
			$keys[7] => $this->getWtvrMessageSubject(),
			$keys[8] => $this->getWtvrMessageBody(),
			$keys[9] => $this->getWtvrMessageText(),
			$keys[10] => $this->getWtvrMessageDate(),
			$keys[11] => $this->getWtvrMessageTemplate(),
			$keys[12] => $this->getWtvrMessageKey1(),
			$keys[13] => $this->getWtvrMessageKey2(),
			$keys[14] => $this->getWtvrMessageKey3(),
			$keys[15] => $this->getWtvrMessageKey4(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = WtvrMessagePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setWtvrMessageId($value);
				break;
			case 1:
				$this->setWtvrMessageIdentifier($value);
				break;
			case 2:
				$this->setWtvrMessageScope($value);
				break;
			case 3:
				$this->setWtvrMessageSendUserId($value);
				break;
			case 4:
				$this->setWtvrMessageSendEmail($value);
				break;
			case 5:
				$this->setWtvrMessageSendFname($value);
				break;
			case 6:
				$this->setWtvrMessageSendLname($value);
				break;
			case 7:
				$this->setWtvrMessageSubject($value);
				break;
			case 8:
				$this->setWtvrMessageBody($value);
				break;
			case 9:
				$this->setWtvrMessageText($value);
				break;
			case 10:
				$this->setWtvrMessageDate($value);
				break;
			case 11:
				$this->setWtvrMessageTemplate($value);
				break;
			case 12:
				$this->setWtvrMessageKey1($value);
				break;
			case 13:
				$this->setWtvrMessageKey2($value);
				break;
			case 14:
				$this->setWtvrMessageKey3($value);
				break;
			case 15:
				$this->setWtvrMessageKey4($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = WtvrMessagePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setWtvrMessageId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setWtvrMessageIdentifier($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setWtvrMessageScope($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setWtvrMessageSendUserId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setWtvrMessageSendEmail($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setWtvrMessageSendFname($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setWtvrMessageSendLname($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setWtvrMessageSubject($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setWtvrMessageBody($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setWtvrMessageText($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setWtvrMessageDate($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setWtvrMessageTemplate($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setWtvrMessageKey1($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setWtvrMessageKey2($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setWtvrMessageKey3($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setWtvrMessageKey4($arr[$keys[15]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(WtvrMessagePeer::DATABASE_NAME);

		if ($this->isColumnModified(WtvrMessagePeer::WTVR_MESSAGE_ID)) $criteria->add(WtvrMessagePeer::WTVR_MESSAGE_ID, $this->wtvr_message_id);
		if ($this->isColumnModified(WtvrMessagePeer::WTVR_MESSAGE_IDENTIFIER)) $criteria->add(WtvrMessagePeer::WTVR_MESSAGE_IDENTIFIER, $this->wtvr_message_identifier);
		if ($this->isColumnModified(WtvrMessagePeer::WTVR_MESSAGE_SCOPE)) $criteria->add(WtvrMessagePeer::WTVR_MESSAGE_SCOPE, $this->wtvr_message_scope);
		if ($this->isColumnModified(WtvrMessagePeer::WTVR_MESSAGE_SEND_USER_ID)) $criteria->add(WtvrMessagePeer::WTVR_MESSAGE_SEND_USER_ID, $this->wtvr_message_send_user_id);
		if ($this->isColumnModified(WtvrMessagePeer::WTVR_MESSAGE_SEND_EMAIL)) $criteria->add(WtvrMessagePeer::WTVR_MESSAGE_SEND_EMAIL, $this->wtvr_message_send_email);
		if ($this->isColumnModified(WtvrMessagePeer::WTVR_MESSAGE_SEND_FNAME)) $criteria->add(WtvrMessagePeer::WTVR_MESSAGE_SEND_FNAME, $this->wtvr_message_send_fname);
		if ($this->isColumnModified(WtvrMessagePeer::WTVR_MESSAGE_SEND_LNAME)) $criteria->add(WtvrMessagePeer::WTVR_MESSAGE_SEND_LNAME, $this->wtvr_message_send_lname);
		if ($this->isColumnModified(WtvrMessagePeer::WTVR_MESSAGE_SUBJECT)) $criteria->add(WtvrMessagePeer::WTVR_MESSAGE_SUBJECT, $this->wtvr_message_subject);
		if ($this->isColumnModified(WtvrMessagePeer::WTVR_MESSAGE_BODY)) $criteria->add(WtvrMessagePeer::WTVR_MESSAGE_BODY, $this->wtvr_message_body);
		if ($this->isColumnModified(WtvrMessagePeer::WTVR_MESSAGE_TEXT)) $criteria->add(WtvrMessagePeer::WTVR_MESSAGE_TEXT, $this->wtvr_message_text);
		if ($this->isColumnModified(WtvrMessagePeer::WTVR_MESSAGE_DATE)) $criteria->add(WtvrMessagePeer::WTVR_MESSAGE_DATE, $this->wtvr_message_date);
		if ($this->isColumnModified(WtvrMessagePeer::WTVR_MESSAGE_TEMPLATE)) $criteria->add(WtvrMessagePeer::WTVR_MESSAGE_TEMPLATE, $this->wtvr_message_template);
		if ($this->isColumnModified(WtvrMessagePeer::WTVR_MESSAGE_KEY1)) $criteria->add(WtvrMessagePeer::WTVR_MESSAGE_KEY1, $this->wtvr_message_key1);
		if ($this->isColumnModified(WtvrMessagePeer::WTVR_MESSAGE_KEY2)) $criteria->add(WtvrMessagePeer::WTVR_MESSAGE_KEY2, $this->wtvr_message_key2);
		if ($this->isColumnModified(WtvrMessagePeer::WTVR_MESSAGE_KEY3)) $criteria->add(WtvrMessagePeer::WTVR_MESSAGE_KEY3, $this->wtvr_message_key3);
		if ($this->isColumnModified(WtvrMessagePeer::WTVR_MESSAGE_KEY4)) $criteria->add(WtvrMessagePeer::WTVR_MESSAGE_KEY4, $this->wtvr_message_key4);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(WtvrMessagePeer::DATABASE_NAME);

		$criteria->add(WtvrMessagePeer::WTVR_MESSAGE_ID, $this->wtvr_message_id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getWtvrMessageId();
	}

	/**
	 * Generic method to set the primary key (wtvr_message_id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setWtvrMessageId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of WtvrMessage (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setWtvrMessageIdentifier($this->wtvr_message_identifier);

		$copyObj->setWtvrMessageScope($this->wtvr_message_scope);

		$copyObj->setWtvrMessageSendUserId($this->wtvr_message_send_user_id);

		$copyObj->setWtvrMessageSendEmail($this->wtvr_message_send_email);

		$copyObj->setWtvrMessageSendFname($this->wtvr_message_send_fname);

		$copyObj->setWtvrMessageSendLname($this->wtvr_message_send_lname);

		$copyObj->setWtvrMessageSubject($this->wtvr_message_subject);

		$copyObj->setWtvrMessageBody($this->wtvr_message_body);

		$copyObj->setWtvrMessageText($this->wtvr_message_text);

		$copyObj->setWtvrMessageDate($this->wtvr_message_date);

		$copyObj->setWtvrMessageTemplate($this->wtvr_message_template);

		$copyObj->setWtvrMessageKey1($this->wtvr_message_key1);

		$copyObj->setWtvrMessageKey2($this->wtvr_message_key2);

		$copyObj->setWtvrMessageKey3($this->wtvr_message_key3);

		$copyObj->setWtvrMessageKey4($this->wtvr_message_key4);


		$copyObj->setNew(true);

		$copyObj->setWtvrMessageId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     WtvrMessage Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     WtvrMessagePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new WtvrMessagePeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseWtvrMessage:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseWtvrMessage::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseWtvrMessage
