<?php

/**
 * Base static class for performing query and update operations on the 'audience' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu 26 Apr 2012 01:25:32 PM EDT
 *
 * @package    lib.model.om
 */
abstract class BaseAudiencePeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'audience';

	/** the related Propel class for this table */
	const OM_CLASS = 'Audience';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.Audience';

	/** the related TableMap class for this table */
	const TM_CLASS = 'AudienceTableMap';
	
	/** The total number of columns. */
	const NUM_COLUMNS = 17;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the AUDIENCE_ID field */
	const AUDIENCE_ID = 'audience.AUDIENCE_ID';

	/** the column name for the AUDIENCE_PAID_STATUS field */
	const AUDIENCE_PAID_STATUS = 'audience.AUDIENCE_PAID_STATUS';

	/** the column name for the FK_USER_ID field */
	const FK_USER_ID = 'audience.FK_USER_ID';

	/** the column name for the FK_SCREENING_ID field */
	const FK_SCREENING_ID = 'audience.FK_SCREENING_ID';

	/** the column name for the FK_SCREENING_UNIQUE_KEY field */
	const FK_SCREENING_UNIQUE_KEY = 'audience.FK_SCREENING_UNIQUE_KEY';

	/** the column name for the FK_PAYMENT_ID field */
	const FK_PAYMENT_ID = 'audience.FK_PAYMENT_ID';

	/** the column name for the AUDIENCE_INVITE_CODE field */
	const AUDIENCE_INVITE_CODE = 'audience.AUDIENCE_INVITE_CODE';

	/** the column name for the AUDIENCE_IP_ADDR field */
	const AUDIENCE_IP_ADDR = 'audience.AUDIENCE_IP_ADDR';

	/** the column name for the AUDIENCE_CREATED_AT field */
	const AUDIENCE_CREATED_AT = 'audience.AUDIENCE_CREATED_AT';

	/** the column name for the AUDIENCE_UPDATED_AT field */
	const AUDIENCE_UPDATED_AT = 'audience.AUDIENCE_UPDATED_AT';

	/** the column name for the AUDIENCE_STATUS field */
	const AUDIENCE_STATUS = 'audience.AUDIENCE_STATUS';

	/** the column name for the AUDIENCE_USERNAME field */
	const AUDIENCE_USERNAME = 'audience.AUDIENCE_USERNAME';

	/** the column name for the AUDIENCE_REVIEW field */
	const AUDIENCE_REVIEW = 'audience.AUDIENCE_REVIEW';

	/** the column name for the AUDIENCE_REVIEW_STATUS field */
	const AUDIENCE_REVIEW_STATUS = 'audience.AUDIENCE_REVIEW_STATUS';

	/** the column name for the AUDIENCE_SHORT_URL field */
	const AUDIENCE_SHORT_URL = 'audience.AUDIENCE_SHORT_URL';

	/** the column name for the AUDIENCE_TICKET_PRICE field */
	const AUDIENCE_TICKET_PRICE = 'audience.AUDIENCE_TICKET_PRICE';

	/** the column name for the AUDIENCE_HMAC_KEY field */
	const AUDIENCE_HMAC_KEY = 'audience.AUDIENCE_HMAC_KEY';

	/**
	 * An identiy map to hold any loaded instances of Audience objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Audience[]
	 */
	public static $instances = array();


	// symfony behavior
	
	/**
	 * Indicates whether the current model includes I18N.
	 */
	const IS_I18N = false;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('AudienceId', 'AudiencePaidStatus', 'FkUserId', 'FkScreeningId', 'FkScreeningUniqueKey', 'FkPaymentId', 'AudienceInviteCode', 'AudienceIpAddr', 'AudienceCreatedAt', 'AudienceUpdatedAt', 'AudienceStatus', 'AudienceUsername', 'AudienceReview', 'AudienceReviewStatus', 'AudienceShortUrl', 'AudienceTicketPrice', 'AudienceHmacKey', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('audienceId', 'audiencePaidStatus', 'fkUserId', 'fkScreeningId', 'fkScreeningUniqueKey', 'fkPaymentId', 'audienceInviteCode', 'audienceIpAddr', 'audienceCreatedAt', 'audienceUpdatedAt', 'audienceStatus', 'audienceUsername', 'audienceReview', 'audienceReviewStatus', 'audienceShortUrl', 'audienceTicketPrice', 'audienceHmacKey', ),
		BasePeer::TYPE_COLNAME => array (self::AUDIENCE_ID, self::AUDIENCE_PAID_STATUS, self::FK_USER_ID, self::FK_SCREENING_ID, self::FK_SCREENING_UNIQUE_KEY, self::FK_PAYMENT_ID, self::AUDIENCE_INVITE_CODE, self::AUDIENCE_IP_ADDR, self::AUDIENCE_CREATED_AT, self::AUDIENCE_UPDATED_AT, self::AUDIENCE_STATUS, self::AUDIENCE_USERNAME, self::AUDIENCE_REVIEW, self::AUDIENCE_REVIEW_STATUS, self::AUDIENCE_SHORT_URL, self::AUDIENCE_TICKET_PRICE, self::AUDIENCE_HMAC_KEY, ),
		BasePeer::TYPE_FIELDNAME => array ('audience_id', 'audience_paid_status', 'fk_user_id', 'fk_screening_id', 'fk_screening_unique_key', 'fk_payment_id', 'audience_invite_code', 'audience_ip_addr', 'audience_created_at', 'audience_updated_at', 'audience_status', 'audience_username', 'audience_review', 'audience_review_status', 'audience_short_url', 'audience_ticket_price', 'audience_hmac_key', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('AudienceId' => 0, 'AudiencePaidStatus' => 1, 'FkUserId' => 2, 'FkScreeningId' => 3, 'FkScreeningUniqueKey' => 4, 'FkPaymentId' => 5, 'AudienceInviteCode' => 6, 'AudienceIpAddr' => 7, 'AudienceCreatedAt' => 8, 'AudienceUpdatedAt' => 9, 'AudienceStatus' => 10, 'AudienceUsername' => 11, 'AudienceReview' => 12, 'AudienceReviewStatus' => 13, 'AudienceShortUrl' => 14, 'AudienceTicketPrice' => 15, 'AudienceHmacKey' => 16, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('audienceId' => 0, 'audiencePaidStatus' => 1, 'fkUserId' => 2, 'fkScreeningId' => 3, 'fkScreeningUniqueKey' => 4, 'fkPaymentId' => 5, 'audienceInviteCode' => 6, 'audienceIpAddr' => 7, 'audienceCreatedAt' => 8, 'audienceUpdatedAt' => 9, 'audienceStatus' => 10, 'audienceUsername' => 11, 'audienceReview' => 12, 'audienceReviewStatus' => 13, 'audienceShortUrl' => 14, 'audienceTicketPrice' => 15, 'audienceHmacKey' => 16, ),
		BasePeer::TYPE_COLNAME => array (self::AUDIENCE_ID => 0, self::AUDIENCE_PAID_STATUS => 1, self::FK_USER_ID => 2, self::FK_SCREENING_ID => 3, self::FK_SCREENING_UNIQUE_KEY => 4, self::FK_PAYMENT_ID => 5, self::AUDIENCE_INVITE_CODE => 6, self::AUDIENCE_IP_ADDR => 7, self::AUDIENCE_CREATED_AT => 8, self::AUDIENCE_UPDATED_AT => 9, self::AUDIENCE_STATUS => 10, self::AUDIENCE_USERNAME => 11, self::AUDIENCE_REVIEW => 12, self::AUDIENCE_REVIEW_STATUS => 13, self::AUDIENCE_SHORT_URL => 14, self::AUDIENCE_TICKET_PRICE => 15, self::AUDIENCE_HMAC_KEY => 16, ),
		BasePeer::TYPE_FIELDNAME => array ('audience_id' => 0, 'audience_paid_status' => 1, 'fk_user_id' => 2, 'fk_screening_id' => 3, 'fk_screening_unique_key' => 4, 'fk_payment_id' => 5, 'audience_invite_code' => 6, 'audience_ip_addr' => 7, 'audience_created_at' => 8, 'audience_updated_at' => 9, 'audience_status' => 10, 'audience_username' => 11, 'audience_review' => 12, 'audience_review_status' => 13, 'audience_short_url' => 14, 'audience_ticket_price' => 15, 'audience_hmac_key' => 16, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, )
	);

	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. AudiencePeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(AudiencePeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{
		$criteria->addSelectColumn(AudiencePeer::AUDIENCE_ID);
		$criteria->addSelectColumn(AudiencePeer::AUDIENCE_PAID_STATUS);
		$criteria->addSelectColumn(AudiencePeer::FK_USER_ID);
		$criteria->addSelectColumn(AudiencePeer::FK_SCREENING_ID);
		$criteria->addSelectColumn(AudiencePeer::FK_SCREENING_UNIQUE_KEY);
		$criteria->addSelectColumn(AudiencePeer::FK_PAYMENT_ID);
		$criteria->addSelectColumn(AudiencePeer::AUDIENCE_INVITE_CODE);
		$criteria->addSelectColumn(AudiencePeer::AUDIENCE_IP_ADDR);
		$criteria->addSelectColumn(AudiencePeer::AUDIENCE_CREATED_AT);
		$criteria->addSelectColumn(AudiencePeer::AUDIENCE_UPDATED_AT);
		$criteria->addSelectColumn(AudiencePeer::AUDIENCE_STATUS);
		$criteria->addSelectColumn(AudiencePeer::AUDIENCE_USERNAME);
		$criteria->addSelectColumn(AudiencePeer::AUDIENCE_REVIEW);
		$criteria->addSelectColumn(AudiencePeer::AUDIENCE_REVIEW_STATUS);
		$criteria->addSelectColumn(AudiencePeer::AUDIENCE_SHORT_URL);
		$criteria->addSelectColumn(AudiencePeer::AUDIENCE_TICKET_PRICE);
		$criteria->addSelectColumn(AudiencePeer::AUDIENCE_HMAC_KEY);
	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(AudiencePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AudiencePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(AudiencePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAudiencePeer', $criteria, $con);
		}

		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Audience
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = AudiencePeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return AudiencePeer::populateObjects(AudiencePeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(AudiencePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			AudiencePeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAudiencePeer', $criteria, $con);
		}


		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Audience $value A Audience object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Audience $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getAudienceId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Audience object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Audience) {
				$key = (string) $value->getAudienceId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Audience object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Audience Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Method to invalidate the instance pool of all tables related to audience
	 * by a foreign key with ON DELETE CASCADE
	 */
	public static function clearRelatedInstancePool()
	{
	}

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol] === null) {
			return null;
		}
		return (string) $row[$startcol];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = AudiencePeer::getOMClass(false);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = AudiencePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = AudiencePeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				AudiencePeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * Add a TableMap instance to the database for this peer class.
	 */
	public static function buildTableMap()
	{
	  $dbMap = Propel::getDatabaseMap(BaseAudiencePeer::DATABASE_NAME);
	  if (!$dbMap->hasTable(BaseAudiencePeer::TABLE_NAME))
	  {
	    $dbMap->addTableObject(new AudienceTableMap());
	  }
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * If $withPrefix is true, the returned path
	 * uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @param      boolean  Whether or not to return the path wit hthe class name 
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass($withPrefix = true)
	{
		return $withPrefix ? AudiencePeer::CLASS_DEFAULT : AudiencePeer::OM_CLASS;
	}

	/**
	 * Method perform an INSERT on the database, given a Audience or Criteria object.
	 *
	 * @param      mixed $values Criteria or Audience object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseAudiencePeer:doInsert:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseAudiencePeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(AudiencePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Audience object
		}

		if ($criteria->containsKey(AudiencePeer::AUDIENCE_ID) && $criteria->keyContainsValue(AudiencePeer::AUDIENCE_ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.AudiencePeer::AUDIENCE_ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseAudiencePeer:doInsert:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseAudiencePeer', $values, $con, $pk);
    }

		return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Audience or Criteria object.
	 *
	 * @param      mixed $values Criteria or Audience object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseAudiencePeer:doUpdate:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseAudiencePeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(AudiencePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(AudiencePeer::AUDIENCE_ID);
			$selectCriteria->add(AudiencePeer::AUDIENCE_ID, $criteria->remove(AudiencePeer::AUDIENCE_ID), $comparison);

		} else { // $values is Audience object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseAudiencePeer:doUpdate:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseAudiencePeer', $values, $con, $ret);
    }

    return $ret;
	}

	/**
	 * Method to DELETE all rows from the audience table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(AudiencePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(AudiencePeer::TABLE_NAME, $con);
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			AudiencePeer::clearInstancePool();
			AudiencePeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Audience or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Audience object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(AudiencePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			AudiencePeer::clearInstancePool();
			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Audience) { // it's a model object
			// invalidate the cache for this single object
			AudiencePeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else { // it's a primary key, or an array of pks
			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(AudiencePeer::AUDIENCE_ID, (array) $values, Criteria::IN);
			// invalidate the cache for this object(s)
			foreach ((array) $values as $singleval) {
				AudiencePeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);
			AudiencePeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given Audience object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Audience $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Audience $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(AudiencePeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(AudiencePeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		return BasePeer::doValidate(AudiencePeer::DATABASE_NAME, AudiencePeer::TABLE_NAME, $columns);
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Audience
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = AudiencePeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(AudiencePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(AudiencePeer::DATABASE_NAME);
		$criteria->add(AudiencePeer::AUDIENCE_ID, $pk);

		$v = AudiencePeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(AudiencePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(AudiencePeer::DATABASE_NAME);
			$criteria->add(AudiencePeer::AUDIENCE_ID, $pks, Criteria::IN);
			$objs = AudiencePeer::doSelect($criteria, $con);
		}
		return $objs;
	}

	// symfony behavior
	
	/**
	 * Returns an array of arrays that contain columns in each unique index.
	 *
	 * @return array
	 */
	static public function getUniqueColumnNames()
	{
	  return array();
	}

	// symfony_behaviors behavior
	
	/**
	 * Returns the name of the hook to call from inside the supplied method.
	 *
	 * @param string $method The calling method
	 *
	 * @return string A hook name for {@link sfMixer}
	 *
	 * @throws LogicException If the method name is not recognized
	 */
	static private function getMixerPreSelectHook($method)
	{
	  if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
	  {
	    return sprintf('BaseAudiencePeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
	  }
	
	  throw new LogicException(sprintf('Unrecognized function "%s"', $method));
	}

} // BaseAudiencePeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BaseAudiencePeer::buildTableMap();

