<?php

/**
 * Base static class for performing query and update operations on the 'log_akamailog' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu 26 Apr 2012 01:25:34 PM EDT
 *
 * @package    lib.model.om
 */
abstract class BaseLogAkamailogPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'log_akamailog';

	/** the related Propel class for this table */
	const OM_CLASS = 'LogAkamailog';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.LogAkamailog';

	/** the related TableMap class for this table */
	const TM_CLASS = 'LogAkamailogTableMap';
	
	/** The total number of columns. */
	const NUM_COLUMNS = 12;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the LOG_AKAMAILOG_ID field */
	const LOG_AKAMAILOG_ID = 'log_akamailog.LOG_AKAMAILOG_ID';

	/** the column name for the LOG_AKAMAILOG_DATE field */
	const LOG_AKAMAILOG_DATE = 'log_akamailog.LOG_AKAMAILOG_DATE';

	/** the column name for the LOG_AKAMAILOG_TIME field */
	const LOG_AKAMAILOG_TIME = 'log_akamailog.LOG_AKAMAILOG_TIME';

	/** the column name for the LOG_AKAMAILOG_IP field */
	const LOG_AKAMAILOG_IP = 'log_akamailog.LOG_AKAMAILOG_IP';

	/** the column name for the LOG_AKAMAILOG_METHOD field */
	const LOG_AKAMAILOG_METHOD = 'log_akamailog.LOG_AKAMAILOG_METHOD';

	/** the column name for the LOG_AKAMAILOG_URI field */
	const LOG_AKAMAILOG_URI = 'log_akamailog.LOG_AKAMAILOG_URI';

	/** the column name for the LOG_AKAMAILOG_STATUS field */
	const LOG_AKAMAILOG_STATUS = 'log_akamailog.LOG_AKAMAILOG_STATUS';

	/** the column name for the LOG_AKAMAILOG_BYTES field */
	const LOG_AKAMAILOG_BYTES = 'log_akamailog.LOG_AKAMAILOG_BYTES';

	/** the column name for the LOG_AKAMAILOG_TIMETAKEN field */
	const LOG_AKAMAILOG_TIMETAKEN = 'log_akamailog.LOG_AKAMAILOG_TIMETAKEN';

	/** the column name for the LOG_AKAMAILOG_REFERER field */
	const LOG_AKAMAILOG_REFERER = 'log_akamailog.LOG_AKAMAILOG_REFERER';

	/** the column name for the LOG_AKAMAILOG_USER_AGENT field */
	const LOG_AKAMAILOG_USER_AGENT = 'log_akamailog.LOG_AKAMAILOG_USER_AGENT';

	/** the column name for the LOG_AKAMAILOG_COOKIE field */
	const LOG_AKAMAILOG_COOKIE = 'log_akamailog.LOG_AKAMAILOG_COOKIE';

	/**
	 * An identiy map to hold any loaded instances of LogAkamailog objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array LogAkamailog[]
	 */
	public static $instances = array();


	// symfony behavior
	
	/**
	 * Indicates whether the current model includes I18N.
	 */
	const IS_I18N = false;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('LogAkamailogId', 'LogAkamailogDate', 'LogAkamailogTime', 'LogAkamailogIp', 'LogAkamailogMethod', 'LogAkamailogUri', 'LogAkamailogStatus', 'LogAkamailogBytes', 'LogAkamailogTimetaken', 'LogAkamailogReferer', 'LogAkamailogUserAgent', 'LogAkamailogCookie', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('logAkamailogId', 'logAkamailogDate', 'logAkamailogTime', 'logAkamailogIp', 'logAkamailogMethod', 'logAkamailogUri', 'logAkamailogStatus', 'logAkamailogBytes', 'logAkamailogTimetaken', 'logAkamailogReferer', 'logAkamailogUserAgent', 'logAkamailogCookie', ),
		BasePeer::TYPE_COLNAME => array (self::LOG_AKAMAILOG_ID, self::LOG_AKAMAILOG_DATE, self::LOG_AKAMAILOG_TIME, self::LOG_AKAMAILOG_IP, self::LOG_AKAMAILOG_METHOD, self::LOG_AKAMAILOG_URI, self::LOG_AKAMAILOG_STATUS, self::LOG_AKAMAILOG_BYTES, self::LOG_AKAMAILOG_TIMETAKEN, self::LOG_AKAMAILOG_REFERER, self::LOG_AKAMAILOG_USER_AGENT, self::LOG_AKAMAILOG_COOKIE, ),
		BasePeer::TYPE_FIELDNAME => array ('log_akamailog_id', 'log_akamailog_date', 'log_akamailog_time', 'log_akamailog_ip', 'log_akamailog_method', 'log_akamailog_uri', 'log_akamailog_status', 'log_akamailog_bytes', 'log_akamailog_timetaken', 'log_akamailog_referer', 'log_akamailog_user_agent', 'log_akamailog_cookie', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('LogAkamailogId' => 0, 'LogAkamailogDate' => 1, 'LogAkamailogTime' => 2, 'LogAkamailogIp' => 3, 'LogAkamailogMethod' => 4, 'LogAkamailogUri' => 5, 'LogAkamailogStatus' => 6, 'LogAkamailogBytes' => 7, 'LogAkamailogTimetaken' => 8, 'LogAkamailogReferer' => 9, 'LogAkamailogUserAgent' => 10, 'LogAkamailogCookie' => 11, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('logAkamailogId' => 0, 'logAkamailogDate' => 1, 'logAkamailogTime' => 2, 'logAkamailogIp' => 3, 'logAkamailogMethod' => 4, 'logAkamailogUri' => 5, 'logAkamailogStatus' => 6, 'logAkamailogBytes' => 7, 'logAkamailogTimetaken' => 8, 'logAkamailogReferer' => 9, 'logAkamailogUserAgent' => 10, 'logAkamailogCookie' => 11, ),
		BasePeer::TYPE_COLNAME => array (self::LOG_AKAMAILOG_ID => 0, self::LOG_AKAMAILOG_DATE => 1, self::LOG_AKAMAILOG_TIME => 2, self::LOG_AKAMAILOG_IP => 3, self::LOG_AKAMAILOG_METHOD => 4, self::LOG_AKAMAILOG_URI => 5, self::LOG_AKAMAILOG_STATUS => 6, self::LOG_AKAMAILOG_BYTES => 7, self::LOG_AKAMAILOG_TIMETAKEN => 8, self::LOG_AKAMAILOG_REFERER => 9, self::LOG_AKAMAILOG_USER_AGENT => 10, self::LOG_AKAMAILOG_COOKIE => 11, ),
		BasePeer::TYPE_FIELDNAME => array ('log_akamailog_id' => 0, 'log_akamailog_date' => 1, 'log_akamailog_time' => 2, 'log_akamailog_ip' => 3, 'log_akamailog_method' => 4, 'log_akamailog_uri' => 5, 'log_akamailog_status' => 6, 'log_akamailog_bytes' => 7, 'log_akamailog_timetaken' => 8, 'log_akamailog_referer' => 9, 'log_akamailog_user_agent' => 10, 'log_akamailog_cookie' => 11, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, )
	);

	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. LogAkamailogPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(LogAkamailogPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{
		$criteria->addSelectColumn(LogAkamailogPeer::LOG_AKAMAILOG_ID);
		$criteria->addSelectColumn(LogAkamailogPeer::LOG_AKAMAILOG_DATE);
		$criteria->addSelectColumn(LogAkamailogPeer::LOG_AKAMAILOG_TIME);
		$criteria->addSelectColumn(LogAkamailogPeer::LOG_AKAMAILOG_IP);
		$criteria->addSelectColumn(LogAkamailogPeer::LOG_AKAMAILOG_METHOD);
		$criteria->addSelectColumn(LogAkamailogPeer::LOG_AKAMAILOG_URI);
		$criteria->addSelectColumn(LogAkamailogPeer::LOG_AKAMAILOG_STATUS);
		$criteria->addSelectColumn(LogAkamailogPeer::LOG_AKAMAILOG_BYTES);
		$criteria->addSelectColumn(LogAkamailogPeer::LOG_AKAMAILOG_TIMETAKEN);
		$criteria->addSelectColumn(LogAkamailogPeer::LOG_AKAMAILOG_REFERER);
		$criteria->addSelectColumn(LogAkamailogPeer::LOG_AKAMAILOG_USER_AGENT);
		$criteria->addSelectColumn(LogAkamailogPeer::LOG_AKAMAILOG_COOKIE);
	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(LogAkamailogPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			LogAkamailogPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(LogAkamailogPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseLogAkamailogPeer', $criteria, $con);
		}

		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     LogAkamailog
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = LogAkamailogPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return LogAkamailogPeer::populateObjects(LogAkamailogPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(LogAkamailogPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			LogAkamailogPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseLogAkamailogPeer', $criteria, $con);
		}


		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      LogAkamailog $value A LogAkamailog object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(LogAkamailog $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getLogAkamailogId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A LogAkamailog object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof LogAkamailog) {
				$key = (string) $value->getLogAkamailogId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or LogAkamailog object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     LogAkamailog Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Method to invalidate the instance pool of all tables related to log_akamailog
	 * by a foreign key with ON DELETE CASCADE
	 */
	public static function clearRelatedInstancePool()
	{
	}

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol] === null) {
			return null;
		}
		return (string) $row[$startcol];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = LogAkamailogPeer::getOMClass(false);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = LogAkamailogPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = LogAkamailogPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				LogAkamailogPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * Add a TableMap instance to the database for this peer class.
	 */
	public static function buildTableMap()
	{
	  $dbMap = Propel::getDatabaseMap(BaseLogAkamailogPeer::DATABASE_NAME);
	  if (!$dbMap->hasTable(BaseLogAkamailogPeer::TABLE_NAME))
	  {
	    $dbMap->addTableObject(new LogAkamailogTableMap());
	  }
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * If $withPrefix is true, the returned path
	 * uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @param      boolean  Whether or not to return the path wit hthe class name 
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass($withPrefix = true)
	{
		return $withPrefix ? LogAkamailogPeer::CLASS_DEFAULT : LogAkamailogPeer::OM_CLASS;
	}

	/**
	 * Method perform an INSERT on the database, given a LogAkamailog or Criteria object.
	 *
	 * @param      mixed $values Criteria or LogAkamailog object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseLogAkamailogPeer:doInsert:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseLogAkamailogPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(LogAkamailogPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from LogAkamailog object
		}

		if ($criteria->containsKey(LogAkamailogPeer::LOG_AKAMAILOG_ID) && $criteria->keyContainsValue(LogAkamailogPeer::LOG_AKAMAILOG_ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.LogAkamailogPeer::LOG_AKAMAILOG_ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseLogAkamailogPeer:doInsert:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseLogAkamailogPeer', $values, $con, $pk);
    }

		return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a LogAkamailog or Criteria object.
	 *
	 * @param      mixed $values Criteria or LogAkamailog object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseLogAkamailogPeer:doUpdate:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseLogAkamailogPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(LogAkamailogPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(LogAkamailogPeer::LOG_AKAMAILOG_ID);
			$selectCriteria->add(LogAkamailogPeer::LOG_AKAMAILOG_ID, $criteria->remove(LogAkamailogPeer::LOG_AKAMAILOG_ID), $comparison);

		} else { // $values is LogAkamailog object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseLogAkamailogPeer:doUpdate:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseLogAkamailogPeer', $values, $con, $ret);
    }

    return $ret;
	}

	/**
	 * Method to DELETE all rows from the log_akamailog table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(LogAkamailogPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(LogAkamailogPeer::TABLE_NAME, $con);
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			LogAkamailogPeer::clearInstancePool();
			LogAkamailogPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a LogAkamailog or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or LogAkamailog object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(LogAkamailogPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			LogAkamailogPeer::clearInstancePool();
			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof LogAkamailog) { // it's a model object
			// invalidate the cache for this single object
			LogAkamailogPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else { // it's a primary key, or an array of pks
			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(LogAkamailogPeer::LOG_AKAMAILOG_ID, (array) $values, Criteria::IN);
			// invalidate the cache for this object(s)
			foreach ((array) $values as $singleval) {
				LogAkamailogPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);
			LogAkamailogPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given LogAkamailog object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      LogAkamailog $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(LogAkamailog $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(LogAkamailogPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(LogAkamailogPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		return BasePeer::doValidate(LogAkamailogPeer::DATABASE_NAME, LogAkamailogPeer::TABLE_NAME, $columns);
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     LogAkamailog
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = LogAkamailogPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(LogAkamailogPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(LogAkamailogPeer::DATABASE_NAME);
		$criteria->add(LogAkamailogPeer::LOG_AKAMAILOG_ID, $pk);

		$v = LogAkamailogPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(LogAkamailogPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(LogAkamailogPeer::DATABASE_NAME);
			$criteria->add(LogAkamailogPeer::LOG_AKAMAILOG_ID, $pks, Criteria::IN);
			$objs = LogAkamailogPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

	// symfony behavior
	
	/**
	 * Returns an array of arrays that contain columns in each unique index.
	 *
	 * @return array
	 */
	static public function getUniqueColumnNames()
	{
	  return array();
	}

	// symfony_behaviors behavior
	
	/**
	 * Returns the name of the hook to call from inside the supplied method.
	 *
	 * @param string $method The calling method
	 *
	 * @return string A hook name for {@link sfMixer}
	 *
	 * @throws LogicException If the method name is not recognized
	 */
	static private function getMixerPreSelectHook($method)
	{
	  if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
	  {
	    return sprintf('BaseLogAkamailogPeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
	  }
	
	  throw new LogicException(sprintf('Unrecognized function "%s"', $method));
	}

} // BaseLogAkamailogPeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BaseLogAkamailogPeer::buildTableMap();

