truncate table wtvr_message;
truncate table wtvr_message_address;
truncate table wtvr_message_queue_global;
truncate table wtvr_message_queue_local;
truncate table wtvr_message_recipient;
truncate table wtvr_message_view;
truncate table user_session;
truncate table audience;
truncate table payment;
truncate table chat_usage;
truncate table chat_instance;
truncate table activity_log;
delete from user where user_id > 100;
