# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false
    web_debug:              false
    cache:                  false
    no_script_name:         on
    etag:                   off
    debug:                  false
    logging_enabled:        off
    use_flash:              off
    use_process_cache:      on
    compressed:             on

stage:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    web_debug:              false
    cache:                  false
    no_script_name:         on
    etag:                   off
    debug:                  true
    logging_enabled:        off
    use_flash:              off
    use_process_cache:      on
    compressed:             on

dev:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         on
    etag:                   off
    debug:                  true
    logging_enabled:        off
    use_flash:              off
    use_process_cache:      on
    compressed:             on

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:       false     # Unique secret to enable CSRF protection or false to disable
    timeout:    false

    # Output escaping settings
    escaping_strategy:      false            # Determines how variables are made available to templates. Accepted values: on, off.
    escaping_method:        ESC_SPECIALCHARS # Function or helper used for escaping. Accepted values: ESC_RAW, ESC_ENTITIES, ESC_JS, ESC_JS_NO_ENTITIES, and ESC_SPECIALCHARS.
    
    generic_action:         true 
    public_key:             ilwjodku2384702lckj3oksd
    
    login_module:           login   # To be called when a non-authenticated user
    login_action:           login     # Tries to access a secure page
    enabled_modules:       [default]
    
    .actions:
      error_404_module:       default   # To be called when a 404 error is raised
      error_404_action:       error404  # Or when the requested URL doesn't match any route
