<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/04/22 17:20:36

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'phptype' => 'mysql',
  'dsn' => 'mysql:host=localhost;dbname=constellation_dev',
  'username' => 'root',
  'password' => '1hsvy5qb',
  'name' => 'propel',
)),

'constellation' => new sfPropelDatabase(array (
  'phptype' => 'mysql',
  'dsn' => 'mysql:host=localhost;dbname=constellation_dev',
  'username' => 'root',
  'password' => '1hsvy5qb',
  'name' => 'constellation',
)),

'constellation_mongo' => new MongoDatabase(array (
  'phptype' => 'mongo',
  'dsn' => '192.168.2.107:constellation_dev',
  'name' => 'constellation_mongo',
)),

'constellation_mongo_session' => new MongoDatabase(array (
  'phptype' => 'mongo',
  'dsn' => '192.168.2.107:constellation_dev',
  'name' => 'constellation_mongo_session',
)),);
