<?php


/**
 * This class defines the structure of the 'click_action' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu 26 Apr 2012 01:25:32 PM EDT
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ClickActionTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ClickActionTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('click_action');
		$this->setPhpName('ClickAction');
		$this->setClassname('ClickAction');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('CLICK_ACTION_ID', 'ClickActionId', 'INTEGER', true, 11, null);
		$this->addColumn('FK_USER_ID', 'FkUserId', 'INTEGER', false, 11, null);
		$this->addColumn('FK_FILM_ID', 'FkFilmId', 'INTEGER', false, 11, null);
		$this->addColumn('FK_SCREENING_ID', 'FkScreeningId', 'INTEGER', false, 11, null);
		$this->addColumn('FK_PAYMENT_ID', 'FkPaymentId', 'INTEGER', false, 11, null);
		$this->addColumn('FK_CLICK_GUID', 'FkClickGuid', 'VARCHAR', false, 255, null);
		$this->addColumn('FK_CLICK_ID', 'FkClickId', 'INTEGER', false, 11, null);
		$this->addColumn('CLICK_ACTION_DATE', 'ClickActionDate', 'TIMESTAMP', false, null, null);
		$this->addColumn('FK_CLICK_ACTION_TYPE', 'FkClickActionType', 'INTEGER', false, 11, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // ClickActionTableMap
