<?php


/**
 * This class defines the structure of the 'invited' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri May 13 11:26:13 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class InvitedTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.InvitedTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('invited');
		$this->setPhpName('Invited');
		$this->setClassname('Invited');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('INVITED_ID', 'InvitedId', 'INTEGER', true, 11, null);
		$this->addColumn('FK_CONTACT_IMPORT_ID', 'FkContactImportId', 'INTEGER', false, 11, null);
		$this->addColumn('FK_MAIL_RUN_ID', 'FkMailRunId', 'INTEGER', false, 11, null);
		$this->addColumn('INVITED_CREATED_AT', 'InvitedCreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('INVITED_UPDATED_AT', 'InvitedUpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // InvitedTableMap
