<?php


/**
 * This class defines the structure of the 'log_akamailog' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu 26 Apr 2012 01:25:34 PM EDT
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class LogAkamailogTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.LogAkamailogTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('log_akamailog');
		$this->setPhpName('LogAkamailog');
		$this->setClassname('LogAkamailog');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('LOG_AKAMAILOG_ID', 'LogAkamailogId', 'INTEGER', true, 11, null);
		$this->addColumn('LOG_AKAMAILOG_DATE', 'LogAkamailogDate', 'DATE', false, null, null);
		$this->addColumn('LOG_AKAMAILOG_TIME', 'LogAkamailogTime', 'TIME', false, null, null);
		$this->addColumn('LOG_AKAMAILOG_IP', 'LogAkamailogIp', 'VARCHAR', false, 255, null);
		$this->addColumn('LOG_AKAMAILOG_METHOD', 'LogAkamailogMethod', 'VARCHAR', false, 255, null);
		$this->addColumn('LOG_AKAMAILOG_URI', 'LogAkamailogUri', 'VARCHAR', false, 255, null);
		$this->addColumn('LOG_AKAMAILOG_STATUS', 'LogAkamailogStatus', 'INTEGER', false, 11, null);
		$this->addColumn('LOG_AKAMAILOG_BYTES', 'LogAkamailogBytes', 'INTEGER', false, 11, null);
		$this->addColumn('LOG_AKAMAILOG_TIMETAKEN', 'LogAkamailogTimetaken', 'BIGINT', false, 20, null);
		$this->addColumn('LOG_AKAMAILOG_REFERER', 'LogAkamailogReferer', 'VARCHAR', false, 255, null);
		$this->addColumn('LOG_AKAMAILOG_USER_AGENT', 'LogAkamailogUserAgent', 'VARCHAR', false, 255, null);
		$this->addColumn('LOG_AKAMAILOG_COOKIE', 'LogAkamailogCookie', 'VARCHAR', false, 255, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // LogAkamailogTableMap
