<?php


/**
 * This class defines the structure of the 'mail_run' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri May 13 11:26:13 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class MailRunTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.MailRunTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('mail_run');
		$this->setPhpName('MailRun');
		$this->setClassname('MailRun');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('MAIL_RUN_ID', 'MailRunId', 'INTEGER', true, 11, null);
		$this->addColumn('FK_INVITATION_ID', 'FkInvitationId', 'INTEGER', false, 11, null);
		$this->addColumn('MAIL_RUN_SUBJECT', 'MailRunSubject', 'VARCHAR', false, 255, null);
		$this->addColumn('MAIL_RUN_BODY', 'MailRunBody', 'LONGVARCHAR', false, null, null);
		$this->addColumn('MAIL_RUN_STATUS', 'MailRunStatus', 'TINYINT', false, 4, null);
		$this->addColumn('MAIL_RUN_CREATED_AT', 'MailRunCreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('MAIL_RUN_UPDATED_AT', 'MailRunUpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // MailRunTableMap
