<?php


/**
 * This class defines the structure of the 'sales_stat' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu 26 Apr 2012 01:25:35 PM EDT
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class SalesStatTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.SalesStatTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('sales_stat');
		$this->setPhpName('SalesStat');
		$this->setClassname('SalesStat');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('SALES_STAT_ID', 'SalesStatId', 'INTEGER', true, 11, null);
		$this->addColumn('SALES_STAT_DATE', 'SalesStatDate', 'TIMESTAMP', false, null, null);
		$this->addColumn('SALES_STAT_SALES_PAYPAL', 'SalesStatSalesPaypal', 'FLOAT', false, 4, null);
		$this->addColumn('SALES_STAT_SALES_PAYPAL_WPP', 'SalesStatSalesPaypalWpp', 'FLOAT', false, 4, null);
		$this->addColumn('SALES_STAT_VISITORS', 'SalesStatVisitors', 'INTEGER', false, 11, null);
		$this->addColumn('SALES_STAT_PAGEVIEWS', 'SalesStatPageviews', 'INTEGER', false, 11, null);
		$this->addColumn('SALES_STAT_TYPE', 'SalesStatType', 'TINYINT', false, 4, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // SalesStatTableMap
