<?php


/**
 * This class defines the structure of the 'seat' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri May 13 11:26:14 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class SeatTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.SeatTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('seat');
		$this->setPhpName('Seat');
		$this->setClassname('Seat');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('SEAT_ID', 'SeatId', 'INTEGER', true, 11, null);
		$this->addColumn('FK_AUDIENCE_ID', 'FkAudienceId', 'INTEGER', false, 11, null);
		$this->addColumn('FK_SCREENING_ID', 'FkScreeningId', 'INTEGER', false, 11, null);
		$this->addColumn('SEAT_IP', 'SeatIp', 'VARCHAR', false, 15, null);
		$this->addColumn('SEAT_STATUS', 'SeatStatus', 'TINYINT', false, 4, null);
		$this->addColumn('SEAT_UNIQUE_ID', 'SeatUniqueId', 'VARCHAR', false, 15, null);
		$this->addColumn('SEAT_CREATED_AT', 'SeatCreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('SEAT_UPDATED_AT', 'SeatUpdatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('SEAT_LAST_CONTACT_AT', 'SeatLastContactAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('SEAT_COOKIE_KEY', 'SeatCookieKey', 'VARCHAR', false, 255, null);
		$this->addColumn('SEAT_LAST_CHAT_AT', 'SeatLastChatAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('SEAT_COORDS', 'SeatCoords', 'VARCHAR', false, 255, null);
		$this->addColumn('SEAT_BROWSER_VERSION', 'SeatBrowserVersion', 'VARCHAR', false, 255, null);
		$this->addColumn('SEAT_OS_VERSION', 'SeatOsVersion', 'VARCHAR', false, 255, null);
		$this->addColumn('SEAT_TIME_SPENT', 'SeatTimeSpent', 'INTEGER', false, 11, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // SeatTableMap
