<?php


/**
 * This class defines the structure of the 'seat_browser' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri May 13 11:26:14 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class SeatBrowserTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.SeatBrowserTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('seat_browser');
		$this->setPhpName('SeatBrowser');
		$this->setClassname('SeatBrowser');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('SEAT_BROWSER_ID', 'SeatBrowserId', 'INTEGER', true, 11, null);
		$this->addColumn('FK_SCREENING_ID', 'FkScreeningId', 'INTEGER', false, 11, null);
		$this->addColumn('FK_SEAT_ID', 'FkSeatId', 'INTEGER', false, 11, null);
		$this->addColumn('SEAT_BROWSER_START_AT', 'SeatBrowserStartAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('SEAT_BROWSER_END_AT', 'SeatBrowserEndAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('SEAT_BROWSER_OS', 'SeatBrowserOs', 'VARCHAR', false, 255, null);
		$this->addColumn('SEAT_BROWSER_BROWSER', 'SeatBrowserBrowser', 'VARCHAR', false, 255, null);
		$this->addColumn('SEAT_BROWSER_USER_AGENT', 'SeatBrowserUserAgent', 'LONGVARCHAR', false, null, null);
		$this->addColumn('SEAT_BROWSER_OS_VERSION', 'SeatBrowserOsVersion', 'VARCHAR', false, 255, null);
		$this->addColumn('SEAT_BROWSER_BROWSER_VERSION', 'SeatBrowserBrowserVersion', 'VARCHAR', false, 255, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // SeatBrowserTableMap
