<?php


/**
 * This class defines the structure of the 'ticket' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri May 13 11:26:14 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class TicketTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.TicketTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('ticket');
		$this->setPhpName('Ticket');
		$this->setClassname('Ticket');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('TICKET_ID', 'TicketId', 'INTEGER', true, 11, null);
		$this->addColumn('TICKET_PAID_STATUS', 'TicketPaidStatus', 'TINYINT', false, 1, 0);
		$this->addColumn('FK_USER_ID', 'FkUserId', 'INTEGER', false, 11, null);
		$this->addColumn('FK_PAYMENT_ID', 'FkPaymentId', 'INTEGER', false, 11, null);
		$this->addColumn('TICKET_INVITE_CODE', 'TicketInviteCode', 'VARCHAR', false, 255, null);
		$this->addColumn('TICKET_IP_ADDR', 'TicketIpAddr', 'VARCHAR', false, 15, null);
		$this->addColumn('TICKET_START_DATE', 'TicketStartDate', 'TIMESTAMP', false, null, null);
		$this->addColumn('TICKET_CREATED_AT', 'TicketCreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('TICKET_UPDATED_AT', 'TicketUpdatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('TICKET_STATUS', 'TicketStatus', 'TINYINT', false, 1, null);
		$this->addColumn('TICKET_USERNAME', 'TicketUsername', 'VARCHAR', false, 255, null);
		$this->addColumn('TICKET_TICKET_PRICE', 'TicketTicketPrice', 'FLOAT', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // TicketTableMap
