<?php


/**
 * This class defines the structure of the 'transaction' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu 26 Apr 2012 01:25:36 PM EDT
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class TransactionTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.TransactionTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('transaction');
		$this->setPhpName('Transaction');
		$this->setClassname('Transaction');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('TRANSACTION_ID', 'TransactionId', 'INTEGER', true, 11, null);
		$this->addColumn('FK_PAYMENT_ID', 'FkPaymentId', 'INTEGER', false, 11, null);
		$this->addColumn('TRANSACTION_NUMBER', 'TransactionNumber', 'VARCHAR', false, 50, null);
		$this->addColumn('TRANSACTION_RESPONSE_OBJECT', 'TransactionResponseObject', 'LONGVARCHAR', false, null, null);
		$this->addColumn('TRANSACTION_GATEWAY_ENVIRONMENT', 'TransactionGatewayEnvironment', 'VARCHAR', false, 50, null);
		$this->addColumn('TRANSACTION_FRAUD_ALERT', 'TransactionFraudAlert', 'VARCHAR', false, 255, null);
		$this->addColumn('TRANSACTION_AUTH_CODE', 'TransactionAuthCode', 'VARCHAR', false, 50, null);
		$this->addColumn('TRANSACTION_STATUS', 'TransactionStatus', 'TINYINT', false, 4, null);
		$this->addColumn('TRANSACTION_CREATED_AT', 'TransactionCreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('TRANSACTION_UPDATED_AT', 'TransactionUpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // TransactionTableMap
