<?php


/**
 * This class defines the structure of the 'wtvr_message_recipient' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu 26 Apr 2012 01:25:37 PM EDT
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class WtvrMessageRecipientTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.WtvrMessageRecipientTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('wtvr_message_recipient');
		$this->setPhpName('WtvrMessageRecipient');
		$this->setClassname('WtvrMessageRecipient');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('WTVR_MESSAGE_RECIPIENT__ID', 'WtvrMessageRecipientId', 'INTEGER', true, 11, null);
		$this->addColumn('FK_WTVR_MESSAGE_ID', 'FkWtvrMessageId', 'INTEGER', false, 11, null);
		$this->addColumn('WTVR_MESSAGE_RECIPIENT_EMAIL', 'WtvrMessageRecipientEmail', 'VARCHAR', false, 255, null);
		$this->addColumn('WTVR_MESSAGE_RECIPIENT_FNAME', 'WtvrMessageRecipientFname', 'VARCHAR', false, 50, null);
		$this->addColumn('WTVR_MESSAGE_RECIPIENT_LNAME', 'WtvrMessageRecipientLname', 'VARCHAR', false, 50, null);
		$this->addColumn('WTVR_MESSAGE_RECIPIENT_DATE_ADDED', 'WtvrMessageRecipientDateAdded', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // WtvrMessageRecipientTableMap
