<?php


/**
 * This class defines the structure of the 'wtvr_message_view' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu 26 Apr 2012 01:25:37 PM EDT
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class WtvrMessageViewTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.WtvrMessageViewTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('wtvr_message_view');
		$this->setPhpName('WtvrMessageView');
		$this->setClassname('WtvrMessageView');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('WTVR_MESSAGE_VIEW_ID', 'WtvrMessageViewId', 'INTEGER', true, 11, null);
		$this->addColumn('FK_WTVR_MESSAGE_ID', 'FkWtvrMessageId', 'INTEGER', false, 11, null);
		$this->addColumn('FK_MESSAGE_RECIPIENT_ID', 'FkMessageRecipientId', 'INTEGER', false, 11, null);
		$this->addColumn('WTVR_MESSAGE_VIEW_DATE_VIEWED', 'WtvrMessageViewDateViewed', 'TIMESTAMP', false, null, null);
		$this->addColumn('WTVR_MESSAGE_VIEW_IP_ADDRESS', 'WtvrMessageViewIpAddress', 'VARCHAR', false, 20, null);
		$this->addColumn('WTVR_MESSAGE_VIEW_BROWSER', 'WtvrMessageViewBrowser', 'VARCHAR', false, 255, null);
		$this->addColumn('WTVR_MESSAGE_VIEW_DATA', 'WtvrMessageViewData', 'LONGVARCHAR', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // WtvrMessageViewTableMap
