#!/bin/sh
#
# mongo - this script starts and stops the nginx daemon
#
# chkconfig:   - 85 15
# description:  Mongo is a NoSQL server
# processname: mongod

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

mongo="/usr/share/mongo/bin/mongod"
prog=$(basename $mongo)

start() {
    echo -n $"Starting $prog: "
    $mongo --rest --dbpath /data/db&
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    for apid in `pidof mongod`
    do
      kill -15 $apid
    done
    #killall $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

case "$1" in
    start)
        $1
        ;;
    stop)
        $1
        ;;
    restart)
        $1
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 2
esac
