<?php


/**
 * Skeleton subclass for representing a row from the 'chat_instance' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Feb  2 12:04:52 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ChatInstance extends BaseChatInstance {

} // ChatInstance
