<?php


/**
 * Skeleton subclass for performing query and update operations on the 'film_sales_template' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri May 13 11:26:13 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class FilmSalesTemplatePeer extends BaseFilmSalesTemplatePeer {

} // FilmSalesTemplatePeer
