<?php


/**
 * Skeleton subclass for performing query and update operations on the 'metric' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri 13 Jan 2012 12:47:22 PM EST
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class MetricPeer extends BaseMetricPeer {

} // MetricPeer
