<?php


/**
 * Skeleton subclass for representing a row from the 'sales_stat' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Jul 11 13:42:37 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class SalesStat extends BaseSalesStat {

} // SalesStat
