<?php


/**
 * Skeleton subclass for representing a row from the 'screening_reminder' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Nov 29 20:21:34 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ScreeningReminder extends BaseScreeningReminder {

} // ScreeningReminder
