<?php


/**
 * Skeleton subclass for performing query and update operations on the 'sponsor_domain' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Apr  1 11:55:45 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class SponsorDomainPeer extends BaseSponsorDomainPeer {

} // SponsorDomainPeer
