<?php


/**
 * Skeleton subclass for performing query and update operations on the 'tokbox_video' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon 06 Feb 2012 06:11:43 PM EST
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TokboxVideoPeer extends BaseTokboxVideoPeer {

} // TokboxVideoPeer
