<?php


/**
 * Skeleton subclass for performing query and update operations on the 'user_payments' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed 18 Jan 2012 04:15:02 PM EST
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class UserPaymentsPeer extends BaseUserPaymentsPeer {

} // UserPaymentsPeer
